/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

// source: pb-cpp/swig.i


extern
#ifdef __cplusplus
  "C"
#endif
  void cgo_panic__pb_d9d2dd81988ff878(const char*);
static void _swig_gopanic(const char *p) {
  cgo_panic__pb_d9d2dd81988ff878(p);
}



#define SWIG_VERSION 0x040301
#define SWIGGO
#define SWIGMODULE pb
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif

#if defined(__cplusplus) && __cplusplus >=201103L
# define SWIG_NULLPTR nullptr
#else
# define SWIG_NULLPTR NULL
#endif 

/* -----------------------------------------------------------------------------
 * swigcompat.swg
 *
 * Macros to provide support compatibility with older C and C++ standards.
 *
 * Note that SWIG expects __cplusplus to be defined to the appropriate C++ standard.
 * MSVC users are urged to check and examine the /Zc:__cplusplus compiler option.
 * See https://learn.microsoft.com/en-us/cpp/build/reference/zc-cplusplus.
 * ----------------------------------------------------------------------------- */

/* C99 and C++11 should provide snprintf, but define SWIG_NO_SNPRINTF
 * if you're missing it.
 */
#if ((defined __STDC_VERSION__ && __STDC_VERSION__ >= 199901L) || \
     (defined __cplusplus && __cplusplus >= 201103L) || \
     defined SWIG_HAVE_SNPRINTF) && \
    !defined SWIG_NO_SNPRINTF
# define SWIG_snprintf(O,S,F,A) snprintf(O,S,F,A)
# define SWIG_snprintf2(O,S,F,A,B) snprintf(O,S,F,A,B)
#else
/* Fallback versions ignore the buffer size, but most of our uses either have a
 * fixed maximum possible size or dynamically allocate a buffer that's large
 * enough.
 */
# define SWIG_snprintf(O,S,F,A) sprintf(O,F,A)
# define SWIG_snprintf2(O,S,F,A,B) sprintf(O,F,A,B)
#endif


#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>



typedef ptrdiff_t intgo;
typedef size_t uintgo;


# if !defined(__clang__) && (defined(__i386__) || defined(__x86_64__))
#   define SWIGSTRUCTPACKED __attribute__((__packed__, __gcc_struct__))
# else
#   define SWIGSTRUCTPACKED __attribute__((__packed__))
# endif



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;



#ifdef __cplusplus
#include <utility>
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigSmartPointer {
    T *ptr;
    SwigSmartPointer(T *p) : ptr(p) { }
    ~SwigSmartPointer() { delete ptr; }
    SwigSmartPointer& operator=(SwigSmartPointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
    void reset(T *p) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = p; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigSmartPointer tmp(new T(t)); pointer = tmp; return *this; }
#if __cplusplus >=201103L
  SwigValueWrapper& operator=(T&& t) { SwigSmartPointer tmp(new T(std::move(t))); pointer = tmp; return *this; }
  operator T&&() const { return std::move(*pointer.ptr); }
#else
  operator T&() const { return *pointer.ptr; }
#endif
  T *operator&() const { return pointer.ptr; }
  static void reset(SwigValueWrapper& t, T *p) { t.pointer.reset(p); }
};

/*
 * SwigValueInit() is a generic initialisation solution as the following approach:
 * 
 *       T c_result = T();
 * 
 * doesn't compile for all types for example:
 * 
 *       unsigned int c_result = unsigned int();
 */
template <typename T> T SwigValueInit() {
  return T();
}

#if __cplusplus >=201103L
# define SWIG_STD_MOVE(OBJ) std::move(OBJ)
#else
# define SWIG_STD_MOVE(OBJ) OBJ
#endif

#endif


static void Swig_free(void* p) {
  free(p);
}

static void* Swig_malloc(int c) {
  return malloc(c);
}


#include "pb.h"

#ifdef __cplusplus
extern "C" {
#endif

void _wrap_Swig_free_pb_d9d2dd81988ff878(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  Swig_free(arg1);
  
}


void *_wrap_Swig_malloc_pb_d9d2dd81988ff878(intgo _swig_go_0) {
  int arg1 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (void *)Swig_malloc(arg1);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


std::vector< char > *_wrap_Value_serialize_pb_d9d2dd81988ff878(Value *_swig_go_0) {
  Value *arg1 = (Value *) 0 ;
  std::vector< char > result;
  std::vector< char > *_swig_go_result;
  
  arg1 = *(Value **)&_swig_go_0; 
  
  result = (arg1)->serialize();
  *(std::vector< char > **)&_swig_go_result = new std::vector< char >(result); 
  return _swig_go_result;
}


Value *_wrap_Value_deserialize_pb_d9d2dd81988ff878(std::vector< char > *_swig_go_0) {
  std::vector< char > arg1 ;
  std::vector< char > *argp1 ;
  Value result;
  Value *_swig_go_result;
  
  
  argp1 = (std::vector< char > *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null std::vector< char >");
  }
  arg1 = (std::vector< char >)*argp1;
  
  
  result = Value::deserialize(SWIG_STD_MOVE(arg1));
  *(Value **)&_swig_go_result = new Value(result); 
  return _swig_go_result;
}


Value *_wrap_new_Value_pb_d9d2dd81988ff878() {
  Value *result = 0 ;
  Value *_swig_go_result;
  
  
  result = (Value *)new Value();
  *(Value **)&_swig_go_result = (Value *)result; 
  return _swig_go_result;
}


void _wrap_delete_Value_pb_d9d2dd81988ff878(Value *_swig_go_0) {
  Value *arg1 = (Value *) 0 ;
  
  arg1 = *(Value **)&_swig_go_0; 
  
  delete arg1;
  
}


Type *_wrap_new_Type_pb_d9d2dd81988ff878() {
  Type *result = 0 ;
  Type *_swig_go_result;
  
  
  result = (Type *)new Type();
  *(Type **)&_swig_go_result = (Type *)result; 
  return _swig_go_result;
}


void _wrap_delete_Type_pb_d9d2dd81988ff878(Type *_swig_go_0) {
  Type *arg1 = (Type *) 0 ;
  
  arg1 = *(Type **)&_swig_go_0; 
  
  delete arg1;
  
}


std::vector< char > *_wrap_Type_serialize_pb_d9d2dd81988ff878(Type *_swig_go_0) {
  Type *arg1 = (Type *) 0 ;
  std::vector< char > result;
  std::vector< char > *_swig_go_result;
  
  arg1 = *(Type **)&_swig_go_0; 
  
  Value *swig_b0 = (Value *)arg1;
  result = (swig_b0)->serialize();
  *(std::vector< char > **)&_swig_go_result = new std::vector< char >(result); 
  return _swig_go_result;
}


Value *_wrap_Type_deserialize_pb_d9d2dd81988ff878(std::vector< char > *_swig_go_0) {
  std::vector< char > arg1 ;
  std::vector< char > *argp1 ;
  Value result;
  Value *_swig_go_result;
  
  
  argp1 = (std::vector< char > *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null std::vector< char >");
  }
  arg1 = (std::vector< char >)*argp1;
  
  
  result = Value::deserialize(SWIG_STD_MOVE(arg1));
  *(Value **)&_swig_go_result = new Value(result); 
  return _swig_go_result;
}


IntType *_wrap_new_IntType_pb_d9d2dd81988ff878() {
  IntType *result = 0 ;
  IntType *_swig_go_result;
  
  
  result = (IntType *)new IntType();
  *(IntType **)&_swig_go_result = (IntType *)result; 
  return _swig_go_result;
}


void _wrap_delete_IntType_pb_d9d2dd81988ff878(IntType *_swig_go_0) {
  IntType *arg1 = (IntType *) 0 ;
  
  arg1 = *(IntType **)&_swig_go_0; 
  
  delete arg1;
  
}


std::vector< char > *_wrap_IntType_serialize_pb_d9d2dd81988ff878(IntType *_swig_go_0) {
  IntType *arg1 = (IntType *) 0 ;
  std::vector< char > result;
  std::vector< char > *_swig_go_result;
  
  arg1 = *(IntType **)&_swig_go_0; 
  
  Type *swig_b0 = (Type *)arg1;
  Value *swig_b1 = (Value *)swig_b0;
  result = (swig_b1)->serialize();
  *(std::vector< char > **)&_swig_go_result = new std::vector< char >(result); 
  return _swig_go_result;
}


Value *_wrap_IntType_deserialize_pb_d9d2dd81988ff878(std::vector< char > *_swig_go_0) {
  std::vector< char > arg1 ;
  std::vector< char > *argp1 ;
  Value result;
  Value *_swig_go_result;
  
  
  argp1 = (std::vector< char > *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null std::vector< char >");
  }
  arg1 = (std::vector< char >)*argp1;
  
  
  result = Value::deserialize(SWIG_STD_MOVE(arg1));
  *(Value **)&_swig_go_result = new Value(result); 
  return _swig_go_result;
}


Float *_wrap_new_Float_pb_d9d2dd81988ff878() {
  Float *result = 0 ;
  Float *_swig_go_result;
  
  
  result = (Float *)new Float();
  *(Float **)&_swig_go_result = (Float *)result; 
  return _swig_go_result;
}


void _wrap_delete_Float_pb_d9d2dd81988ff878(Float *_swig_go_0) {
  Float *arg1 = (Float *) 0 ;
  
  arg1 = *(Float **)&_swig_go_0; 
  
  delete arg1;
  
}


std::vector< char > *_wrap_Float_serialize_pb_d9d2dd81988ff878(Float *_swig_go_0) {
  Float *arg1 = (Float *) 0 ;
  std::vector< char > result;
  std::vector< char > *_swig_go_result;
  
  arg1 = *(Float **)&_swig_go_0; 
  
  Type *swig_b0 = (Type *)arg1;
  Value *swig_b1 = (Value *)swig_b0;
  result = (swig_b1)->serialize();
  *(std::vector< char > **)&_swig_go_result = new std::vector< char >(result); 
  return _swig_go_result;
}


Value *_wrap_Float_deserialize_pb_d9d2dd81988ff878(std::vector< char > *_swig_go_0) {
  std::vector< char > arg1 ;
  std::vector< char > *argp1 ;
  Value result;
  Value *_swig_go_result;
  
  
  argp1 = (std::vector< char > *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null std::vector< char >");
  }
  arg1 = (std::vector< char >)*argp1;
  
  
  result = Value::deserialize(SWIG_STD_MOVE(arg1));
  *(Value **)&_swig_go_result = new Value(result); 
  return _swig_go_result;
}


BoolType *_wrap_new_BoolType_pb_d9d2dd81988ff878() {
  BoolType *result = 0 ;
  BoolType *_swig_go_result;
  
  
  result = (BoolType *)new BoolType();
  *(BoolType **)&_swig_go_result = (BoolType *)result; 
  return _swig_go_result;
}


void _wrap_delete_BoolType_pb_d9d2dd81988ff878(BoolType *_swig_go_0) {
  BoolType *arg1 = (BoolType *) 0 ;
  
  arg1 = *(BoolType **)&_swig_go_0; 
  
  delete arg1;
  
}


std::vector< char > *_wrap_BoolType_serialize_pb_d9d2dd81988ff878(BoolType *_swig_go_0) {
  BoolType *arg1 = (BoolType *) 0 ;
  std::vector< char > result;
  std::vector< char > *_swig_go_result;
  
  arg1 = *(BoolType **)&_swig_go_0; 
  
  Type *swig_b0 = (Type *)arg1;
  Value *swig_b1 = (Value *)swig_b0;
  result = (swig_b1)->serialize();
  *(std::vector< char > **)&_swig_go_result = new std::vector< char >(result); 
  return _swig_go_result;
}


Value *_wrap_BoolType_deserialize_pb_d9d2dd81988ff878(std::vector< char > *_swig_go_0) {
  std::vector< char > arg1 ;
  std::vector< char > *argp1 ;
  Value result;
  Value *_swig_go_result;
  
  
  argp1 = (std::vector< char > *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null std::vector< char >");
  }
  arg1 = (std::vector< char >)*argp1;
  
  
  result = Value::deserialize(SWIG_STD_MOVE(arg1));
  *(Value **)&_swig_go_result = new Value(result); 
  return _swig_go_result;
}


StringType *_wrap_new_StringType_pb_d9d2dd81988ff878() {
  StringType *result = 0 ;
  StringType *_swig_go_result;
  
  
  result = (StringType *)new StringType();
  *(StringType **)&_swig_go_result = (StringType *)result; 
  return _swig_go_result;
}


void _wrap_delete_StringType_pb_d9d2dd81988ff878(StringType *_swig_go_0) {
  StringType *arg1 = (StringType *) 0 ;
  
  arg1 = *(StringType **)&_swig_go_0; 
  
  delete arg1;
  
}


std::vector< char > *_wrap_StringType_serialize_pb_d9d2dd81988ff878(StringType *_swig_go_0) {
  StringType *arg1 = (StringType *) 0 ;
  std::vector< char > result;
  std::vector< char > *_swig_go_result;
  
  arg1 = *(StringType **)&_swig_go_0; 
  
  Type *swig_b0 = (Type *)arg1;
  Value *swig_b1 = (Value *)swig_b0;
  result = (swig_b1)->serialize();
  *(std::vector< char > **)&_swig_go_result = new std::vector< char >(result); 
  return _swig_go_result;
}


Value *_wrap_StringType_deserialize_pb_d9d2dd81988ff878(std::vector< char > *_swig_go_0) {
  std::vector< char > arg1 ;
  std::vector< char > *argp1 ;
  Value result;
  Value *_swig_go_result;
  
  
  argp1 = (std::vector< char > *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null std::vector< char >");
  }
  arg1 = (std::vector< char >)*argp1;
  
  
  result = Value::deserialize(SWIG_STD_MOVE(arg1));
  *(Value **)&_swig_go_result = new Value(result); 
  return _swig_go_result;
}


void _wrap_TupleType_elements_set_pb_d9d2dd81988ff878(TupleType *_swig_go_0, std::vector< Type > *_swig_go_1) {
  TupleType *arg1 = (TupleType *) 0 ;
  std::vector< Type > *arg2 = (std::vector< Type > *) 0 ;
  
  arg1 = *(TupleType **)&_swig_go_0; 
  arg2 = *(std::vector< Type > **)&_swig_go_1; 
  
  if (arg1) (arg1)->elements = *arg2;
  
}


std::vector< Type > *_wrap_TupleType_elements_get_pb_d9d2dd81988ff878(TupleType *_swig_go_0) {
  TupleType *arg1 = (TupleType *) 0 ;
  std::vector< Type > *result = 0 ;
  std::vector< Type > *_swig_go_result;
  
  arg1 = *(TupleType **)&_swig_go_0; 
  
  result = (std::vector< Type > *)& ((arg1)->elements);
  *(std::vector< Type > **)&_swig_go_result = (std::vector< Type > *)result; 
  return _swig_go_result;
}


TupleType *_wrap_new_TupleType_pb_d9d2dd81988ff878() {
  TupleType *result = 0 ;
  TupleType *_swig_go_result;
  
  
  result = (TupleType *)new TupleType();
  *(TupleType **)&_swig_go_result = (TupleType *)result; 
  return _swig_go_result;
}


void _wrap_delete_TupleType_pb_d9d2dd81988ff878(TupleType *_swig_go_0) {
  TupleType *arg1 = (TupleType *) 0 ;
  
  arg1 = *(TupleType **)&_swig_go_0; 
  
  delete arg1;
  
}


std::vector< char > *_wrap_TupleType_serialize_pb_d9d2dd81988ff878(TupleType *_swig_go_0) {
  TupleType *arg1 = (TupleType *) 0 ;
  std::vector< char > result;
  std::vector< char > *_swig_go_result;
  
  arg1 = *(TupleType **)&_swig_go_0; 
  
  Type *swig_b0 = (Type *)arg1;
  Value *swig_b1 = (Value *)swig_b0;
  result = (swig_b1)->serialize();
  *(std::vector< char > **)&_swig_go_result = new std::vector< char >(result); 
  return _swig_go_result;
}


Value *_wrap_TupleType_deserialize_pb_d9d2dd81988ff878(std::vector< char > *_swig_go_0) {
  std::vector< char > arg1 ;
  std::vector< char > *argp1 ;
  Value result;
  Value *_swig_go_result;
  
  
  argp1 = (std::vector< char > *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null std::vector< char >");
  }
  arg1 = (std::vector< char >)*argp1;
  
  
  result = Value::deserialize(SWIG_STD_MOVE(arg1));
  *(Value **)&_swig_go_result = new Value(result); 
  return _swig_go_result;
}


void _wrap_ListType_element_set_pb_d9d2dd81988ff878(ListType *_swig_go_0, Type *_swig_go_1) {
  ListType *arg1 = (ListType *) 0 ;
  Type *arg2 = (Type *) 0 ;
  
  arg1 = *(ListType **)&_swig_go_0; 
  arg2 = *(Type **)&_swig_go_1; 
  
  if (arg1) (arg1)->element = *arg2;
  
}


Type *_wrap_ListType_element_get_pb_d9d2dd81988ff878(ListType *_swig_go_0) {
  ListType *arg1 = (ListType *) 0 ;
  Type *result = 0 ;
  Type *_swig_go_result;
  
  arg1 = *(ListType **)&_swig_go_0; 
  
  result = (Type *)& ((arg1)->element);
  *(Type **)&_swig_go_result = (Type *)result; 
  return _swig_go_result;
}


ListType *_wrap_new_ListType_pb_d9d2dd81988ff878() {
  ListType *result = 0 ;
  ListType *_swig_go_result;
  
  
  result = (ListType *)new ListType();
  *(ListType **)&_swig_go_result = (ListType *)result; 
  return _swig_go_result;
}


void _wrap_delete_ListType_pb_d9d2dd81988ff878(ListType *_swig_go_0) {
  ListType *arg1 = (ListType *) 0 ;
  
  arg1 = *(ListType **)&_swig_go_0; 
  
  delete arg1;
  
}


std::vector< char > *_wrap_ListType_serialize_pb_d9d2dd81988ff878(ListType *_swig_go_0) {
  ListType *arg1 = (ListType *) 0 ;
  std::vector< char > result;
  std::vector< char > *_swig_go_result;
  
  arg1 = *(ListType **)&_swig_go_0; 
  
  Type *swig_b0 = (Type *)arg1;
  Value *swig_b1 = (Value *)swig_b0;
  result = (swig_b1)->serialize();
  *(std::vector< char > **)&_swig_go_result = new std::vector< char >(result); 
  return _swig_go_result;
}


Value *_wrap_ListType_deserialize_pb_d9d2dd81988ff878(std::vector< char > *_swig_go_0) {
  std::vector< char > arg1 ;
  std::vector< char > *argp1 ;
  Value result;
  Value *_swig_go_result;
  
  
  argp1 = (std::vector< char > *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null std::vector< char >");
  }
  arg1 = (std::vector< char >)*argp1;
  
  
  result = Value::deserialize(SWIG_STD_MOVE(arg1));
  *(Value **)&_swig_go_result = new Value(result); 
  return _swig_go_result;
}


void _wrap_FnType_argument_set_pb_d9d2dd81988ff878(FnType *_swig_go_0, Type *_swig_go_1) {
  FnType *arg1 = (FnType *) 0 ;
  Type *arg2 = (Type *) 0 ;
  
  arg1 = *(FnType **)&_swig_go_0; 
  arg2 = *(Type **)&_swig_go_1; 
  
  if (arg1) (arg1)->argument = *arg2;
  
}


Type *_wrap_FnType_argument_get_pb_d9d2dd81988ff878(FnType *_swig_go_0) {
  FnType *arg1 = (FnType *) 0 ;
  Type *result = 0 ;
  Type *_swig_go_result;
  
  arg1 = *(FnType **)&_swig_go_0; 
  
  result = (Type *)& ((arg1)->argument);
  *(Type **)&_swig_go_result = (Type *)result; 
  return _swig_go_result;
}


void _wrap_FnType__return_set_pb_d9d2dd81988ff878(FnType *_swig_go_0, Type *_swig_go_1) {
  FnType *arg1 = (FnType *) 0 ;
  Type *arg2 = (Type *) 0 ;
  
  arg1 = *(FnType **)&_swig_go_0; 
  arg2 = *(Type **)&_swig_go_1; 
  
  if (arg1) (arg1)->_return = *arg2;
  
}


Type *_wrap_FnType__return_get_pb_d9d2dd81988ff878(FnType *_swig_go_0) {
  FnType *arg1 = (FnType *) 0 ;
  Type *result = 0 ;
  Type *_swig_go_result;
  
  arg1 = *(FnType **)&_swig_go_0; 
  
  result = (Type *)& ((arg1)->_return);
  *(Type **)&_swig_go_result = (Type *)result; 
  return _swig_go_result;
}


FnType *_wrap_new_FnType_pb_d9d2dd81988ff878() {
  FnType *result = 0 ;
  FnType *_swig_go_result;
  
  
  result = (FnType *)new FnType();
  *(FnType **)&_swig_go_result = (FnType *)result; 
  return _swig_go_result;
}


void _wrap_delete_FnType_pb_d9d2dd81988ff878(FnType *_swig_go_0) {
  FnType *arg1 = (FnType *) 0 ;
  
  arg1 = *(FnType **)&_swig_go_0; 
  
  delete arg1;
  
}


std::vector< char > *_wrap_FnType_serialize_pb_d9d2dd81988ff878(FnType *_swig_go_0) {
  FnType *arg1 = (FnType *) 0 ;
  std::vector< char > result;
  std::vector< char > *_swig_go_result;
  
  arg1 = *(FnType **)&_swig_go_0; 
  
  Type *swig_b0 = (Type *)arg1;
  Value *swig_b1 = (Value *)swig_b0;
  result = (swig_b1)->serialize();
  *(std::vector< char > **)&_swig_go_result = new std::vector< char >(result); 
  return _swig_go_result;
}


Value *_wrap_FnType_deserialize_pb_d9d2dd81988ff878(std::vector< char > *_swig_go_0) {
  std::vector< char > arg1 ;
  std::vector< char > *argp1 ;
  Value result;
  Value *_swig_go_result;
  
  
  argp1 = (std::vector< char > *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null std::vector< char >");
  }
  arg1 = (std::vector< char >)*argp1;
  
  
  result = Value::deserialize(SWIG_STD_MOVE(arg1));
  *(Value **)&_swig_go_result = new Value(result); 
  return _swig_go_result;
}


void _wrap_StructType_name_set_pb_d9d2dd81988ff878(StructType *_swig_go_0, std::string *_swig_go_1) {
  StructType *arg1 = (StructType *) 0 ;
  std::string arg2 ;
  std::string *argp2 ;
  
  arg1 = *(StructType **)&_swig_go_0; 
  
  argp2 = (std::string *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null std::string");
  }
  arg2 = (std::string)*argp2;
  
  
  if (arg1) (arg1)->name = arg2;
  
}


std::string *_wrap_StructType_name_get_pb_d9d2dd81988ff878(StructType *_swig_go_0) {
  StructType *arg1 = (StructType *) 0 ;
  std::string result;
  std::string *_swig_go_result;
  
  arg1 = *(StructType **)&_swig_go_0; 
  
  result =  ((arg1)->name);
  *(std::string **)&_swig_go_result = new std::string(result); 
  return _swig_go_result;
}


StructType *_wrap_new_StructType_pb_d9d2dd81988ff878() {
  StructType *result = 0 ;
  StructType *_swig_go_result;
  
  
  result = (StructType *)new StructType();
  *(StructType **)&_swig_go_result = (StructType *)result; 
  return _swig_go_result;
}


void _wrap_delete_StructType_pb_d9d2dd81988ff878(StructType *_swig_go_0) {
  StructType *arg1 = (StructType *) 0 ;
  
  arg1 = *(StructType **)&_swig_go_0; 
  
  delete arg1;
  
}


std::vector< char > *_wrap_StructType_serialize_pb_d9d2dd81988ff878(StructType *_swig_go_0) {
  StructType *arg1 = (StructType *) 0 ;
  std::vector< char > result;
  std::vector< char > *_swig_go_result;
  
  arg1 = *(StructType **)&_swig_go_0; 
  
  Type *swig_b0 = (Type *)arg1;
  Value *swig_b1 = (Value *)swig_b0;
  result = (swig_b1)->serialize();
  *(std::vector< char > **)&_swig_go_result = new std::vector< char >(result); 
  return _swig_go_result;
}


Value *_wrap_StructType_deserialize_pb_d9d2dd81988ff878(std::vector< char > *_swig_go_0) {
  std::vector< char > arg1 ;
  std::vector< char > *argp1 ;
  Value result;
  Value *_swig_go_result;
  
  
  argp1 = (std::vector< char > *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null std::vector< char >");
  }
  arg1 = (std::vector< char >)*argp1;
  
  
  result = Value::deserialize(SWIG_STD_MOVE(arg1));
  *(Value **)&_swig_go_result = new Value(result); 
  return _swig_go_result;
}


Expression *_wrap_new_Expression_pb_d9d2dd81988ff878() {
  Expression *result = 0 ;
  Expression *_swig_go_result;
  
  
  result = (Expression *)new Expression();
  *(Expression **)&_swig_go_result = (Expression *)result; 
  return _swig_go_result;
}


void _wrap_delete_Expression_pb_d9d2dd81988ff878(Expression *_swig_go_0) {
  Expression *arg1 = (Expression *) 0 ;
  
  arg1 = *(Expression **)&_swig_go_0; 
  
  delete arg1;
  
}


std::vector< char > *_wrap_Expression_serialize_pb_d9d2dd81988ff878(Expression *_swig_go_0) {
  Expression *arg1 = (Expression *) 0 ;
  std::vector< char > result;
  std::vector< char > *_swig_go_result;
  
  arg1 = *(Expression **)&_swig_go_0; 
  
  Value *swig_b0 = (Value *)arg1;
  result = (swig_b0)->serialize();
  *(std::vector< char > **)&_swig_go_result = new std::vector< char >(result); 
  return _swig_go_result;
}


Value *_wrap_Expression_deserialize_pb_d9d2dd81988ff878(std::vector< char > *_swig_go_0) {
  std::vector< char > arg1 ;
  std::vector< char > *argp1 ;
  Value result;
  Value *_swig_go_result;
  
  
  argp1 = (std::vector< char > *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null std::vector< char >");
  }
  arg1 = (std::vector< char >)*argp1;
  
  
  result = Value::deserialize(SWIG_STD_MOVE(arg1));
  *(Value **)&_swig_go_result = new Value(result); 
  return _swig_go_result;
}


void _wrap_String_value_set_pb_d9d2dd81988ff878(String *_swig_go_0, std::string *_swig_go_1) {
  String *arg1 = (String *) 0 ;
  std::string arg2 ;
  std::string *argp2 ;
  
  arg1 = *(String **)&_swig_go_0; 
  
  argp2 = (std::string *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null std::string");
  }
  arg2 = (std::string)*argp2;
  
  
  if (arg1) (arg1)->value = arg2;
  
}


std::string *_wrap_String_value_get_pb_d9d2dd81988ff878(String *_swig_go_0) {
  String *arg1 = (String *) 0 ;
  std::string result;
  std::string *_swig_go_result;
  
  arg1 = *(String **)&_swig_go_0; 
  
  result =  ((arg1)->value);
  *(std::string **)&_swig_go_result = new std::string(result); 
  return _swig_go_result;
}


String *_wrap_new_String_pb_d9d2dd81988ff878() {
  String *result = 0 ;
  String *_swig_go_result;
  
  
  result = (String *)new String();
  *(String **)&_swig_go_result = (String *)result; 
  return _swig_go_result;
}


void _wrap_delete_String_pb_d9d2dd81988ff878(String *_swig_go_0) {
  String *arg1 = (String *) 0 ;
  
  arg1 = *(String **)&_swig_go_0; 
  
  delete arg1;
  
}


std::vector< char > *_wrap_String_serialize_pb_d9d2dd81988ff878(String *_swig_go_0) {
  String *arg1 = (String *) 0 ;
  std::vector< char > result;
  std::vector< char > *_swig_go_result;
  
  arg1 = *(String **)&_swig_go_0; 
  
  Expression *swig_b0 = (Expression *)arg1;
  Value *swig_b1 = (Value *)swig_b0;
  result = (swig_b1)->serialize();
  *(std::vector< char > **)&_swig_go_result = new std::vector< char >(result); 
  return _swig_go_result;
}


Value *_wrap_String_deserialize_pb_d9d2dd81988ff878(std::vector< char > *_swig_go_0) {
  std::vector< char > arg1 ;
  std::vector< char > *argp1 ;
  Value result;
  Value *_swig_go_result;
  
  
  argp1 = (std::vector< char > *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null std::vector< char >");
  }
  arg1 = (std::vector< char >)*argp1;
  
  
  result = Value::deserialize(SWIG_STD_MOVE(arg1));
  *(Value **)&_swig_go_result = new Value(result); 
  return _swig_go_result;
}


#ifdef __cplusplus
}
#endif

