// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: schema.capnp

#pragma once

#include <capnp/generated-header-support.h>
#include <kj/windows-sanity.h>

#ifndef CAPNP_VERSION
#error "CAPNP_VERSION is not defined, is capnp/generated-header-support.h missing?"
#elif CAPNP_VERSION != 1000001
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif


CAPNP_BEGIN_HEADER

namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA(ad454f2956d96537);
CAPNP_DECLARE_SCHEMA(e6a9443313a9ccd0);
CAPNP_DECLARE_SCHEMA(dedda0837830d1e1);
CAPNP_DECLARE_SCHEMA(808c155f1add2002);

}  // namespace schemas
}  // namespace capnp


struct Value {
  Value() = delete;

  class Reader;
  class Builder;
  class Pipeline;
  enum Which: uint16_t {
    EMPTY,
    TYPE,
  };
  struct Type;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(ad454f2956d96537, 1, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct Value::Type {
  Type() = delete;

  class Reader;
  class Builder;
  class Pipeline;
  enum Which: uint16_t {
    TYPE,
    INT,
    FLOAT,
    BOOL,
    STRING,
    NIL,
    FN,
    TUPLE,
    LIST,
    STRUC,
  };
  struct Fn;
  struct Struc;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(e6a9443313a9ccd0, 1, 2)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct Value::Type::Fn {
  Fn() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(dedda0837830d1e1, 1, 2)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct Value::Type::Struc {
  Struc() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(808c155f1add2002, 1, 2)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

// =======================================================================================

class Value::Reader {
public:
  typedef Value Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline Which which() const;
  inline bool isEmpty() const;
  inline  ::capnp::Void getEmpty() const;

  inline bool isType() const;
  inline bool hasType() const;
  inline  ::Value::Type::Reader getType() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class Value::Builder {
public:
  typedef Value Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline Which which();
  inline bool isEmpty();
  inline  ::capnp::Void getEmpty();
  inline void setEmpty( ::capnp::Void value = ::capnp::VOID);

  inline bool isType();
  inline bool hasType();
  inline  ::Value::Type::Builder getType();
  inline void setType( ::Value::Type::Reader value);
  inline  ::Value::Type::Builder initType();
  inline void adoptType(::capnp::Orphan< ::Value::Type>&& value);
  inline ::capnp::Orphan< ::Value::Type> disownType();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class Value::Pipeline {
public:
  typedef Value Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class Value::Type::Reader {
public:
  typedef Type Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline Which which() const;
  inline bool isType() const;
  inline  ::capnp::Void getType() const;

  inline bool isInt() const;
  inline  ::capnp::Void getInt() const;

  inline bool isFloat() const;
  inline  ::capnp::Void getFloat() const;

  inline bool isBool() const;
  inline  ::capnp::Void getBool() const;

  inline bool isString() const;
  inline  ::capnp::Void getString() const;

  inline bool isNil() const;
  inline  ::capnp::Void getNil() const;

  inline bool isFn() const;
  inline typename Fn::Reader getFn() const;

  inline bool isTuple() const;
  inline bool hasTuple() const;
  inline  ::capnp::List< ::Value::Type,  ::capnp::Kind::STRUCT>::Reader getTuple() const;

  inline bool isList() const;
  inline bool hasList() const;
  inline  ::Value::Type::Reader getList() const;

  inline bool isStruc() const;
  inline typename Struc::Reader getStruc() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class Value::Type::Builder {
public:
  typedef Type Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline Which which();
  inline bool isType();
  inline  ::capnp::Void getType();
  inline void setType( ::capnp::Void value = ::capnp::VOID);

  inline bool isInt();
  inline  ::capnp::Void getInt();
  inline void setInt( ::capnp::Void value = ::capnp::VOID);

  inline bool isFloat();
  inline  ::capnp::Void getFloat();
  inline void setFloat( ::capnp::Void value = ::capnp::VOID);

  inline bool isBool();
  inline  ::capnp::Void getBool();
  inline void setBool( ::capnp::Void value = ::capnp::VOID);

  inline bool isString();
  inline  ::capnp::Void getString();
  inline void setString( ::capnp::Void value = ::capnp::VOID);

  inline bool isNil();
  inline  ::capnp::Void getNil();
  inline void setNil( ::capnp::Void value = ::capnp::VOID);

  inline bool isFn();
  inline typename Fn::Builder getFn();
  inline typename Fn::Builder initFn();

  inline bool isTuple();
  inline bool hasTuple();
  inline  ::capnp::List< ::Value::Type,  ::capnp::Kind::STRUCT>::Builder getTuple();
  inline void setTuple( ::capnp::List< ::Value::Type,  ::capnp::Kind::STRUCT>::Reader value);
  inline  ::capnp::List< ::Value::Type,  ::capnp::Kind::STRUCT>::Builder initTuple(unsigned int size);
  inline void adoptTuple(::capnp::Orphan< ::capnp::List< ::Value::Type,  ::capnp::Kind::STRUCT>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::Value::Type,  ::capnp::Kind::STRUCT>> disownTuple();

  inline bool isList();
  inline bool hasList();
  inline  ::Value::Type::Builder getList();
  inline void setList( ::Value::Type::Reader value);
  inline  ::Value::Type::Builder initList();
  inline void adoptList(::capnp::Orphan< ::Value::Type>&& value);
  inline ::capnp::Orphan< ::Value::Type> disownList();

  inline bool isStruc();
  inline typename Struc::Builder getStruc();
  inline typename Struc::Builder initStruc();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class Value::Type::Pipeline {
public:
  typedef Type Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class Value::Type::Fn::Reader {
public:
  typedef Fn Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasArgument() const;
  inline  ::Value::Type::Reader getArgument() const;

  inline bool hasReturn() const;
  inline  ::Value::Type::Reader getReturn() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class Value::Type::Fn::Builder {
public:
  typedef Fn Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasArgument();
  inline  ::Value::Type::Builder getArgument();
  inline void setArgument( ::Value::Type::Reader value);
  inline  ::Value::Type::Builder initArgument();
  inline void adoptArgument(::capnp::Orphan< ::Value::Type>&& value);
  inline ::capnp::Orphan< ::Value::Type> disownArgument();

  inline bool hasReturn();
  inline  ::Value::Type::Builder getReturn();
  inline void setReturn( ::Value::Type::Reader value);
  inline  ::Value::Type::Builder initReturn();
  inline void adoptReturn(::capnp::Orphan< ::Value::Type>&& value);
  inline ::capnp::Orphan< ::Value::Type> disownReturn();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class Value::Type::Fn::Pipeline {
public:
  typedef Fn Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

  inline  ::Value::Type::Pipeline getArgument();
  inline  ::Value::Type::Pipeline getReturn();
private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class Value::Type::Struc::Reader {
public:
  typedef Struc Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasName() const;
  inline  ::capnp::Text::Reader getName() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class Value::Type::Struc::Builder {
public:
  typedef Struc Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasName();
  inline  ::capnp::Text::Builder getName();
  inline void setName( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initName(unsigned int size);
  inline void adoptName(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownName();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class Value::Type::Struc::Pipeline {
public:
  typedef Struc Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

// =======================================================================================

inline  ::Value::Which Value::Reader::which() const {
  return _reader.getDataField<Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline  ::Value::Which Value::Builder::which() {
  return _builder.getDataField<Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline bool Value::Reader::isEmpty() const {
  return which() == Value::EMPTY;
}
inline bool Value::Builder::isEmpty() {
  return which() == Value::EMPTY;
}
inline  ::capnp::Void Value::Reader::getEmpty() const {
  KJ_IREQUIRE((which() == Value::EMPTY),
              "Must check which() before get()ing a union member.");
  return _reader.getDataField< ::capnp::Void>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::capnp::Void Value::Builder::getEmpty() {
  KJ_IREQUIRE((which() == Value::EMPTY),
              "Must check which() before get()ing a union member.");
  return _builder.getDataField< ::capnp::Void>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void Value::Builder::setEmpty( ::capnp::Void value) {
  _builder.setDataField<Value::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Value::EMPTY);
  _builder.setDataField< ::capnp::Void>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline bool Value::Reader::isType() const {
  return which() == Value::TYPE;
}
inline bool Value::Builder::isType() {
  return which() == Value::TYPE;
}
inline bool Value::Reader::hasType() const {
  if (which() != Value::TYPE) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Value::Builder::hasType() {
  if (which() != Value::TYPE) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::Value::Type::Reader Value::Reader::getType() const {
  KJ_IREQUIRE((which() == Value::TYPE),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::Value::Type>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::Value::Type::Builder Value::Builder::getType() {
  KJ_IREQUIRE((which() == Value::TYPE),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::Value::Type>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Value::Builder::setType( ::Value::Type::Reader value) {
  _builder.setDataField<Value::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Value::TYPE);
  ::capnp::_::PointerHelpers< ::Value::Type>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::Value::Type::Builder Value::Builder::initType() {
  _builder.setDataField<Value::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Value::TYPE);
  return ::capnp::_::PointerHelpers< ::Value::Type>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Value::Builder::adoptType(
    ::capnp::Orphan< ::Value::Type>&& value) {
  _builder.setDataField<Value::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Value::TYPE);
  ::capnp::_::PointerHelpers< ::Value::Type>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::Value::Type> Value::Builder::disownType() {
  KJ_IREQUIRE((which() == Value::TYPE),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::Value::Type>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline  ::Value::Type::Which Value::Type::Reader::which() const {
  return _reader.getDataField<Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline  ::Value::Type::Which Value::Type::Builder::which() {
  return _builder.getDataField<Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline bool Value::Type::Reader::isType() const {
  return which() == Value::Type::TYPE;
}
inline bool Value::Type::Builder::isType() {
  return which() == Value::Type::TYPE;
}
inline  ::capnp::Void Value::Type::Reader::getType() const {
  KJ_IREQUIRE((which() == Value::Type::TYPE),
              "Must check which() before get()ing a union member.");
  return _reader.getDataField< ::capnp::Void>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::capnp::Void Value::Type::Builder::getType() {
  KJ_IREQUIRE((which() == Value::Type::TYPE),
              "Must check which() before get()ing a union member.");
  return _builder.getDataField< ::capnp::Void>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void Value::Type::Builder::setType( ::capnp::Void value) {
  _builder.setDataField<Value::Type::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Value::Type::TYPE);
  _builder.setDataField< ::capnp::Void>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline bool Value::Type::Reader::isInt() const {
  return which() == Value::Type::INT;
}
inline bool Value::Type::Builder::isInt() {
  return which() == Value::Type::INT;
}
inline  ::capnp::Void Value::Type::Reader::getInt() const {
  KJ_IREQUIRE((which() == Value::Type::INT),
              "Must check which() before get()ing a union member.");
  return _reader.getDataField< ::capnp::Void>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::capnp::Void Value::Type::Builder::getInt() {
  KJ_IREQUIRE((which() == Value::Type::INT),
              "Must check which() before get()ing a union member.");
  return _builder.getDataField< ::capnp::Void>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void Value::Type::Builder::setInt( ::capnp::Void value) {
  _builder.setDataField<Value::Type::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Value::Type::INT);
  _builder.setDataField< ::capnp::Void>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline bool Value::Type::Reader::isFloat() const {
  return which() == Value::Type::FLOAT;
}
inline bool Value::Type::Builder::isFloat() {
  return which() == Value::Type::FLOAT;
}
inline  ::capnp::Void Value::Type::Reader::getFloat() const {
  KJ_IREQUIRE((which() == Value::Type::FLOAT),
              "Must check which() before get()ing a union member.");
  return _reader.getDataField< ::capnp::Void>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::capnp::Void Value::Type::Builder::getFloat() {
  KJ_IREQUIRE((which() == Value::Type::FLOAT),
              "Must check which() before get()ing a union member.");
  return _builder.getDataField< ::capnp::Void>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void Value::Type::Builder::setFloat( ::capnp::Void value) {
  _builder.setDataField<Value::Type::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Value::Type::FLOAT);
  _builder.setDataField< ::capnp::Void>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline bool Value::Type::Reader::isBool() const {
  return which() == Value::Type::BOOL;
}
inline bool Value::Type::Builder::isBool() {
  return which() == Value::Type::BOOL;
}
inline  ::capnp::Void Value::Type::Reader::getBool() const {
  KJ_IREQUIRE((which() == Value::Type::BOOL),
              "Must check which() before get()ing a union member.");
  return _reader.getDataField< ::capnp::Void>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::capnp::Void Value::Type::Builder::getBool() {
  KJ_IREQUIRE((which() == Value::Type::BOOL),
              "Must check which() before get()ing a union member.");
  return _builder.getDataField< ::capnp::Void>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void Value::Type::Builder::setBool( ::capnp::Void value) {
  _builder.setDataField<Value::Type::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Value::Type::BOOL);
  _builder.setDataField< ::capnp::Void>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline bool Value::Type::Reader::isString() const {
  return which() == Value::Type::STRING;
}
inline bool Value::Type::Builder::isString() {
  return which() == Value::Type::STRING;
}
inline  ::capnp::Void Value::Type::Reader::getString() const {
  KJ_IREQUIRE((which() == Value::Type::STRING),
              "Must check which() before get()ing a union member.");
  return _reader.getDataField< ::capnp::Void>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::capnp::Void Value::Type::Builder::getString() {
  KJ_IREQUIRE((which() == Value::Type::STRING),
              "Must check which() before get()ing a union member.");
  return _builder.getDataField< ::capnp::Void>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void Value::Type::Builder::setString( ::capnp::Void value) {
  _builder.setDataField<Value::Type::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Value::Type::STRING);
  _builder.setDataField< ::capnp::Void>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline bool Value::Type::Reader::isNil() const {
  return which() == Value::Type::NIL;
}
inline bool Value::Type::Builder::isNil() {
  return which() == Value::Type::NIL;
}
inline  ::capnp::Void Value::Type::Reader::getNil() const {
  KJ_IREQUIRE((which() == Value::Type::NIL),
              "Must check which() before get()ing a union member.");
  return _reader.getDataField< ::capnp::Void>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::capnp::Void Value::Type::Builder::getNil() {
  KJ_IREQUIRE((which() == Value::Type::NIL),
              "Must check which() before get()ing a union member.");
  return _builder.getDataField< ::capnp::Void>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void Value::Type::Builder::setNil( ::capnp::Void value) {
  _builder.setDataField<Value::Type::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Value::Type::NIL);
  _builder.setDataField< ::capnp::Void>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline bool Value::Type::Reader::isFn() const {
  return which() == Value::Type::FN;
}
inline bool Value::Type::Builder::isFn() {
  return which() == Value::Type::FN;
}
inline typename Value::Type::Fn::Reader Value::Type::Reader::getFn() const {
  KJ_IREQUIRE((which() == Value::Type::FN),
              "Must check which() before get()ing a union member.");
  return typename Value::Type::Fn::Reader(_reader);
}
inline typename Value::Type::Fn::Builder Value::Type::Builder::getFn() {
  KJ_IREQUIRE((which() == Value::Type::FN),
              "Must check which() before get()ing a union member.");
  return typename Value::Type::Fn::Builder(_builder);
}
inline typename Value::Type::Fn::Builder Value::Type::Builder::initFn() {
  _builder.setDataField<Value::Type::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Value::Type::FN);
  _builder.getPointerField(::capnp::bounded<0>() * ::capnp::POINTERS).clear();
  _builder.getPointerField(::capnp::bounded<1>() * ::capnp::POINTERS).clear();
  return typename Value::Type::Fn::Builder(_builder);
}
inline bool Value::Type::Reader::isTuple() const {
  return which() == Value::Type::TUPLE;
}
inline bool Value::Type::Builder::isTuple() {
  return which() == Value::Type::TUPLE;
}
inline bool Value::Type::Reader::hasTuple() const {
  if (which() != Value::Type::TUPLE) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Value::Type::Builder::hasTuple() {
  if (which() != Value::Type::TUPLE) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::Value::Type,  ::capnp::Kind::STRUCT>::Reader Value::Type::Reader::getTuple() const {
  KJ_IREQUIRE((which() == Value::Type::TUPLE),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::capnp::List< ::Value::Type,  ::capnp::Kind::STRUCT>>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::List< ::Value::Type,  ::capnp::Kind::STRUCT>::Builder Value::Type::Builder::getTuple() {
  KJ_IREQUIRE((which() == Value::Type::TUPLE),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::capnp::List< ::Value::Type,  ::capnp::Kind::STRUCT>>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Value::Type::Builder::setTuple( ::capnp::List< ::Value::Type,  ::capnp::Kind::STRUCT>::Reader value) {
  _builder.setDataField<Value::Type::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Value::Type::TUPLE);
  ::capnp::_::PointerHelpers< ::capnp::List< ::Value::Type,  ::capnp::Kind::STRUCT>>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::Value::Type,  ::capnp::Kind::STRUCT>::Builder Value::Type::Builder::initTuple(unsigned int size) {
  _builder.setDataField<Value::Type::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Value::Type::TUPLE);
  return ::capnp::_::PointerHelpers< ::capnp::List< ::Value::Type,  ::capnp::Kind::STRUCT>>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void Value::Type::Builder::adoptTuple(
    ::capnp::Orphan< ::capnp::List< ::Value::Type,  ::capnp::Kind::STRUCT>>&& value) {
  _builder.setDataField<Value::Type::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Value::Type::TUPLE);
  ::capnp::_::PointerHelpers< ::capnp::List< ::Value::Type,  ::capnp::Kind::STRUCT>>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::Value::Type,  ::capnp::Kind::STRUCT>> Value::Type::Builder::disownTuple() {
  KJ_IREQUIRE((which() == Value::Type::TUPLE),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::capnp::List< ::Value::Type,  ::capnp::Kind::STRUCT>>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Value::Type::Reader::isList() const {
  return which() == Value::Type::LIST;
}
inline bool Value::Type::Builder::isList() {
  return which() == Value::Type::LIST;
}
inline bool Value::Type::Reader::hasList() const {
  if (which() != Value::Type::LIST) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Value::Type::Builder::hasList() {
  if (which() != Value::Type::LIST) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::Value::Type::Reader Value::Type::Reader::getList() const {
  KJ_IREQUIRE((which() == Value::Type::LIST),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::Value::Type>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::Value::Type::Builder Value::Type::Builder::getList() {
  KJ_IREQUIRE((which() == Value::Type::LIST),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::Value::Type>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Value::Type::Builder::setList( ::Value::Type::Reader value) {
  _builder.setDataField<Value::Type::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Value::Type::LIST);
  ::capnp::_::PointerHelpers< ::Value::Type>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::Value::Type::Builder Value::Type::Builder::initList() {
  _builder.setDataField<Value::Type::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Value::Type::LIST);
  return ::capnp::_::PointerHelpers< ::Value::Type>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Value::Type::Builder::adoptList(
    ::capnp::Orphan< ::Value::Type>&& value) {
  _builder.setDataField<Value::Type::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Value::Type::LIST);
  ::capnp::_::PointerHelpers< ::Value::Type>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::Value::Type> Value::Type::Builder::disownList() {
  KJ_IREQUIRE((which() == Value::Type::LIST),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::Value::Type>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Value::Type::Reader::isStruc() const {
  return which() == Value::Type::STRUC;
}
inline bool Value::Type::Builder::isStruc() {
  return which() == Value::Type::STRUC;
}
inline typename Value::Type::Struc::Reader Value::Type::Reader::getStruc() const {
  KJ_IREQUIRE((which() == Value::Type::STRUC),
              "Must check which() before get()ing a union member.");
  return typename Value::Type::Struc::Reader(_reader);
}
inline typename Value::Type::Struc::Builder Value::Type::Builder::getStruc() {
  KJ_IREQUIRE((which() == Value::Type::STRUC),
              "Must check which() before get()ing a union member.");
  return typename Value::Type::Struc::Builder(_builder);
}
inline typename Value::Type::Struc::Builder Value::Type::Builder::initStruc() {
  _builder.setDataField<Value::Type::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Value::Type::STRUC);
  _builder.getPointerField(::capnp::bounded<0>() * ::capnp::POINTERS).clear();
  return typename Value::Type::Struc::Builder(_builder);
}
inline bool Value::Type::Fn::Reader::hasArgument() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Value::Type::Fn::Builder::hasArgument() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::Value::Type::Reader Value::Type::Fn::Reader::getArgument() const {
  return ::capnp::_::PointerHelpers< ::Value::Type>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::Value::Type::Builder Value::Type::Fn::Builder::getArgument() {
  return ::capnp::_::PointerHelpers< ::Value::Type>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
#if !CAPNP_LITE
inline  ::Value::Type::Pipeline Value::Type::Fn::Pipeline::getArgument() {
  return  ::Value::Type::Pipeline(_typeless.getPointerField(0));
}
#endif  // !CAPNP_LITE
inline void Value::Type::Fn::Builder::setArgument( ::Value::Type::Reader value) {
  ::capnp::_::PointerHelpers< ::Value::Type>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::Value::Type::Builder Value::Type::Fn::Builder::initArgument() {
  return ::capnp::_::PointerHelpers< ::Value::Type>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Value::Type::Fn::Builder::adoptArgument(
    ::capnp::Orphan< ::Value::Type>&& value) {
  ::capnp::_::PointerHelpers< ::Value::Type>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::Value::Type> Value::Type::Fn::Builder::disownArgument() {
  return ::capnp::_::PointerHelpers< ::Value::Type>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Value::Type::Fn::Reader::hasReturn() const {
  return !_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline bool Value::Type::Fn::Builder::hasReturn() {
  return !_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline  ::Value::Type::Reader Value::Type::Fn::Reader::getReturn() const {
  return ::capnp::_::PointerHelpers< ::Value::Type>::get(_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline  ::Value::Type::Builder Value::Type::Fn::Builder::getReturn() {
  return ::capnp::_::PointerHelpers< ::Value::Type>::get(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
#if !CAPNP_LITE
inline  ::Value::Type::Pipeline Value::Type::Fn::Pipeline::getReturn() {
  return  ::Value::Type::Pipeline(_typeless.getPointerField(1));
}
#endif  // !CAPNP_LITE
inline void Value::Type::Fn::Builder::setReturn( ::Value::Type::Reader value) {
  ::capnp::_::PointerHelpers< ::Value::Type>::set(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), value);
}
inline  ::Value::Type::Builder Value::Type::Fn::Builder::initReturn() {
  return ::capnp::_::PointerHelpers< ::Value::Type>::init(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline void Value::Type::Fn::Builder::adoptReturn(
    ::capnp::Orphan< ::Value::Type>&& value) {
  ::capnp::_::PointerHelpers< ::Value::Type>::adopt(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::Value::Type> Value::Type::Fn::Builder::disownReturn() {
  return ::capnp::_::PointerHelpers< ::Value::Type>::disown(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}

inline bool Value::Type::Struc::Reader::hasName() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Value::Type::Struc::Builder::hasName() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader Value::Type::Struc::Reader::getName() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder Value::Type::Struc::Builder::getName() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Value::Type::Struc::Builder::setName( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder Value::Type::Struc::Builder::initName(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void Value::Type::Struc::Builder::adoptName(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> Value::Type::Struc::Builder::disownName() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}


CAPNP_END_HEADER

