/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

// source: pb-cpp/swig.i

package pb

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stddef.h>
#include <stdint.h>


typedef ptrdiff_t intgo;
typedef size_t uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


extern void _wrap_Swig_free_pb_d9d2dd81988ff878(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_pb_d9d2dd81988ff878(swig_intgo arg1);
extern uintptr_t _wrap_Value_serialize_pb_d9d2dd81988ff878(uintptr_t arg1);
extern uintptr_t _wrap_Value_deserialize_pb_d9d2dd81988ff878(uintptr_t arg1);
extern uintptr_t _wrap_new_Value_pb_d9d2dd81988ff878(void);
extern void _wrap_delete_Value_pb_d9d2dd81988ff878(uintptr_t arg1);
extern uintptr_t _wrap_new_Type_pb_d9d2dd81988ff878(void);
extern void _wrap_delete_Type_pb_d9d2dd81988ff878(uintptr_t arg1);
extern uintptr_t _wrap_Type_serialize_pb_d9d2dd81988ff878(uintptr_t _swig_base);
extern uintptr_t _wrap_Type_deserialize_pb_d9d2dd81988ff878(uintptr_t arg1);
extern uintptr_t _wrap_new_IntType_pb_d9d2dd81988ff878(void);
extern void _wrap_delete_IntType_pb_d9d2dd81988ff878(uintptr_t arg1);
extern uintptr_t _wrap_IntType_serialize_pb_d9d2dd81988ff878(uintptr_t _swig_base);
extern uintptr_t _wrap_IntType_deserialize_pb_d9d2dd81988ff878(uintptr_t arg1);
extern uintptr_t _wrap_new_Float_pb_d9d2dd81988ff878(void);
extern void _wrap_delete_Float_pb_d9d2dd81988ff878(uintptr_t arg1);
extern uintptr_t _wrap_Float_serialize_pb_d9d2dd81988ff878(uintptr_t _swig_base);
extern uintptr_t _wrap_Float_deserialize_pb_d9d2dd81988ff878(uintptr_t arg1);
extern uintptr_t _wrap_new_BoolType_pb_d9d2dd81988ff878(void);
extern void _wrap_delete_BoolType_pb_d9d2dd81988ff878(uintptr_t arg1);
extern uintptr_t _wrap_BoolType_serialize_pb_d9d2dd81988ff878(uintptr_t _swig_base);
extern uintptr_t _wrap_BoolType_deserialize_pb_d9d2dd81988ff878(uintptr_t arg1);
extern uintptr_t _wrap_new_StringType_pb_d9d2dd81988ff878(void);
extern void _wrap_delete_StringType_pb_d9d2dd81988ff878(uintptr_t arg1);
extern uintptr_t _wrap_StringType_serialize_pb_d9d2dd81988ff878(uintptr_t _swig_base);
extern uintptr_t _wrap_StringType_deserialize_pb_d9d2dd81988ff878(uintptr_t arg1);
extern void _wrap_TupleType_elements_set_pb_d9d2dd81988ff878(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_TupleType_elements_get_pb_d9d2dd81988ff878(uintptr_t arg1);
extern uintptr_t _wrap_new_TupleType_pb_d9d2dd81988ff878(void);
extern void _wrap_delete_TupleType_pb_d9d2dd81988ff878(uintptr_t arg1);
extern uintptr_t _wrap_TupleType_serialize_pb_d9d2dd81988ff878(uintptr_t _swig_base);
extern uintptr_t _wrap_TupleType_deserialize_pb_d9d2dd81988ff878(uintptr_t arg1);
extern void _wrap_ListType_element_set_pb_d9d2dd81988ff878(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_ListType_element_get_pb_d9d2dd81988ff878(uintptr_t arg1);
extern uintptr_t _wrap_new_ListType_pb_d9d2dd81988ff878(void);
extern void _wrap_delete_ListType_pb_d9d2dd81988ff878(uintptr_t arg1);
extern uintptr_t _wrap_ListType_serialize_pb_d9d2dd81988ff878(uintptr_t _swig_base);
extern uintptr_t _wrap_ListType_deserialize_pb_d9d2dd81988ff878(uintptr_t arg1);
extern void _wrap_FnType_argument_set_pb_d9d2dd81988ff878(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_FnType_argument_get_pb_d9d2dd81988ff878(uintptr_t arg1);
extern void _wrap_FnType__return_set_pb_d9d2dd81988ff878(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_FnType__return_get_pb_d9d2dd81988ff878(uintptr_t arg1);
extern uintptr_t _wrap_new_FnType_pb_d9d2dd81988ff878(void);
extern void _wrap_delete_FnType_pb_d9d2dd81988ff878(uintptr_t arg1);
extern uintptr_t _wrap_FnType_serialize_pb_d9d2dd81988ff878(uintptr_t _swig_base);
extern uintptr_t _wrap_FnType_deserialize_pb_d9d2dd81988ff878(uintptr_t arg1);
extern void _wrap_StructType_name_set_pb_d9d2dd81988ff878(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_StructType_name_get_pb_d9d2dd81988ff878(uintptr_t arg1);
extern uintptr_t _wrap_new_StructType_pb_d9d2dd81988ff878(void);
extern void _wrap_delete_StructType_pb_d9d2dd81988ff878(uintptr_t arg1);
extern uintptr_t _wrap_StructType_serialize_pb_d9d2dd81988ff878(uintptr_t _swig_base);
extern uintptr_t _wrap_StructType_deserialize_pb_d9d2dd81988ff878(uintptr_t arg1);
extern uintptr_t _wrap_new_Expression_pb_d9d2dd81988ff878(void);
extern void _wrap_delete_Expression_pb_d9d2dd81988ff878(uintptr_t arg1);
extern uintptr_t _wrap_Expression_serialize_pb_d9d2dd81988ff878(uintptr_t _swig_base);
extern uintptr_t _wrap_Expression_deserialize_pb_d9d2dd81988ff878(uintptr_t arg1);
extern void _wrap_String_value_set_pb_d9d2dd81988ff878(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_String_value_get_pb_d9d2dd81988ff878(uintptr_t arg1);
extern uintptr_t _wrap_new_String_pb_d9d2dd81988ff878(void);
extern void _wrap_delete_String_pb_d9d2dd81988ff878(uintptr_t arg1);
extern uintptr_t _wrap_String_serialize_pb_d9d2dd81988ff878(uintptr_t _swig_base);
extern uintptr_t _wrap_String_deserialize_pb_d9d2dd81988ff878(uintptr_t arg1);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


func getSwigcptr(v interface { Swigcptr() uintptr }) uintptr {
	if v == nil {
		return 0
	}
	return v.Swigcptr()
}


type _ sync.Mutex

//export cgo_panic__pb_d9d2dd81988ff878
func cgo_panic__pb_d9d2dd81988ff878(p *byte) {
	s := (*[1024]byte)(unsafe.Pointer(p))[:]
	for i, b := range s {
		if b == 0 {
			panic(string(s[:i]))
		}
	}
	panic(string(s))
}

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_pb_d9d2dd81988ff878(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_pb_d9d2dd81988ff878(C.swig_intgo(_swig_i_0)))
	return swig_r
}

type SwigcptrValue uintptr

func (p SwigcptrValue) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrValue) SwigIsValue() {
}

func (arg1 SwigcptrValue) Serialize() (_swig_ret Std_vector_Sl_char_Sg_) {
	var swig_r Std_vector_Sl_char_Sg_
	_swig_i_0 := arg1
	swig_r = (Std_vector_Sl_char_Sg_)(SwigcptrStd_vector_Sl_char_Sg_(C._wrap_Value_serialize_pb_d9d2dd81988ff878(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func ValueDeserialize(arg1 Std_vector_Sl_char_Sg_) (_swig_ret Value) {
	var swig_r Value
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (Value)(SwigcptrValue(C._wrap_Value_deserialize_pb_d9d2dd81988ff878(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewValue() (_swig_ret Value) {
	var swig_r Value
	swig_r = (Value)(SwigcptrValue(C._wrap_new_Value_pb_d9d2dd81988ff878()))
	return swig_r
}

func DeleteValue(arg1 Value) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_Value_pb_d9d2dd81988ff878(C.uintptr_t(_swig_i_0))
}

type Value interface {
	Swigcptr() uintptr
	SwigIsValue()
	Serialize() (_swig_ret Std_vector_Sl_char_Sg_)
}

type SwigcptrType uintptr

func (p SwigcptrType) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrType) SwigIsType() {
}

func NewType() (_swig_ret Type) {
	var swig_r Type
	swig_r = (Type)(SwigcptrType(C._wrap_new_Type_pb_d9d2dd81988ff878()))
	return swig_r
}

func DeleteType(arg1 Type) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_Type_pb_d9d2dd81988ff878(C.uintptr_t(_swig_i_0))
}

func (_swig_base SwigcptrType) Serialize() (_swig_ret Std_vector_Sl_char_Sg_) {
	var swig_r Std_vector_Sl_char_Sg_
	swig_r = (Std_vector_Sl_char_Sg_)(SwigcptrStd_vector_Sl_char_Sg_(C._wrap_Type_serialize_pb_d9d2dd81988ff878(C.uintptr_t(_swig_base))))
	return swig_r
}

func TypeDeserialize(arg1 Std_vector_Sl_char_Sg_) (_swig_ret Value) {
	var swig_r Value
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (Value)(SwigcptrValue(C._wrap_Type_deserialize_pb_d9d2dd81988ff878(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (p SwigcptrType) SwigIsValue() {
}

func (p SwigcptrType) SwigGetValue() Value {
	return SwigcptrValue(getSwigcptr(p))
}

type Type interface {
	Swigcptr() uintptr
	SwigIsType()
	Serialize() (_swig_ret Std_vector_Sl_char_Sg_)
	SwigIsValue()
	SwigGetValue() Value
}

type SwigcptrIntType uintptr

func (p SwigcptrIntType) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrIntType) SwigIsIntType() {
}

func NewIntType() (_swig_ret IntType) {
	var swig_r IntType
	swig_r = (IntType)(SwigcptrIntType(C._wrap_new_IntType_pb_d9d2dd81988ff878()))
	return swig_r
}

func DeleteIntType(arg1 IntType) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_IntType_pb_d9d2dd81988ff878(C.uintptr_t(_swig_i_0))
}

func (_swig_base SwigcptrIntType) Serialize() (_swig_ret Std_vector_Sl_char_Sg_) {
	var swig_r Std_vector_Sl_char_Sg_
	swig_r = (Std_vector_Sl_char_Sg_)(SwigcptrStd_vector_Sl_char_Sg_(C._wrap_IntType_serialize_pb_d9d2dd81988ff878(C.uintptr_t(_swig_base))))
	return swig_r
}

func IntTypeDeserialize(arg1 Std_vector_Sl_char_Sg_) (_swig_ret Value) {
	var swig_r Value
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (Value)(SwigcptrValue(C._wrap_IntType_deserialize_pb_d9d2dd81988ff878(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (p SwigcptrIntType) SwigIsType() {
}

func (p SwigcptrIntType) SwigGetType() Type {
	return SwigcptrType(getSwigcptr(p))
}

func (p SwigcptrIntType) SwigIsValue() {
}

func (p SwigcptrIntType) SwigGetValue() Value {
	return SwigcptrValue(getSwigcptr(p))
}

type IntType interface {
	Swigcptr() uintptr
	SwigIsIntType()
	Serialize() (_swig_ret Std_vector_Sl_char_Sg_)
	SwigIsType()
	SwigGetType() Type
	SwigIsValue()
	SwigGetValue() Value
}

type SwigcptrFloat uintptr

func (p SwigcptrFloat) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrFloat) SwigIsFloat() {
}

func NewFloat() (_swig_ret Float) {
	var swig_r Float
	swig_r = (Float)(SwigcptrFloat(C._wrap_new_Float_pb_d9d2dd81988ff878()))
	return swig_r
}

func DeleteFloat(arg1 Float) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_Float_pb_d9d2dd81988ff878(C.uintptr_t(_swig_i_0))
}

func (_swig_base SwigcptrFloat) Serialize() (_swig_ret Std_vector_Sl_char_Sg_) {
	var swig_r Std_vector_Sl_char_Sg_
	swig_r = (Std_vector_Sl_char_Sg_)(SwigcptrStd_vector_Sl_char_Sg_(C._wrap_Float_serialize_pb_d9d2dd81988ff878(C.uintptr_t(_swig_base))))
	return swig_r
}

func FloatDeserialize(arg1 Std_vector_Sl_char_Sg_) (_swig_ret Value) {
	var swig_r Value
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (Value)(SwigcptrValue(C._wrap_Float_deserialize_pb_d9d2dd81988ff878(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (p SwigcptrFloat) SwigIsType() {
}

func (p SwigcptrFloat) SwigGetType() Type {
	return SwigcptrType(getSwigcptr(p))
}

func (p SwigcptrFloat) SwigIsValue() {
}

func (p SwigcptrFloat) SwigGetValue() Value {
	return SwigcptrValue(getSwigcptr(p))
}

type Float interface {
	Swigcptr() uintptr
	SwigIsFloat()
	Serialize() (_swig_ret Std_vector_Sl_char_Sg_)
	SwigIsType()
	SwigGetType() Type
	SwigIsValue()
	SwigGetValue() Value
}

type SwigcptrBoolType uintptr

func (p SwigcptrBoolType) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrBoolType) SwigIsBoolType() {
}

func NewBoolType() (_swig_ret BoolType) {
	var swig_r BoolType
	swig_r = (BoolType)(SwigcptrBoolType(C._wrap_new_BoolType_pb_d9d2dd81988ff878()))
	return swig_r
}

func DeleteBoolType(arg1 BoolType) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_BoolType_pb_d9d2dd81988ff878(C.uintptr_t(_swig_i_0))
}

func (_swig_base SwigcptrBoolType) Serialize() (_swig_ret Std_vector_Sl_char_Sg_) {
	var swig_r Std_vector_Sl_char_Sg_
	swig_r = (Std_vector_Sl_char_Sg_)(SwigcptrStd_vector_Sl_char_Sg_(C._wrap_BoolType_serialize_pb_d9d2dd81988ff878(C.uintptr_t(_swig_base))))
	return swig_r
}

func BoolTypeDeserialize(arg1 Std_vector_Sl_char_Sg_) (_swig_ret Value) {
	var swig_r Value
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (Value)(SwigcptrValue(C._wrap_BoolType_deserialize_pb_d9d2dd81988ff878(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (p SwigcptrBoolType) SwigIsType() {
}

func (p SwigcptrBoolType) SwigGetType() Type {
	return SwigcptrType(getSwigcptr(p))
}

func (p SwigcptrBoolType) SwigIsValue() {
}

func (p SwigcptrBoolType) SwigGetValue() Value {
	return SwigcptrValue(getSwigcptr(p))
}

type BoolType interface {
	Swigcptr() uintptr
	SwigIsBoolType()
	Serialize() (_swig_ret Std_vector_Sl_char_Sg_)
	SwigIsType()
	SwigGetType() Type
	SwigIsValue()
	SwigGetValue() Value
}

type SwigcptrStringType uintptr

func (p SwigcptrStringType) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrStringType) SwigIsStringType() {
}

func NewStringType() (_swig_ret StringType) {
	var swig_r StringType
	swig_r = (StringType)(SwigcptrStringType(C._wrap_new_StringType_pb_d9d2dd81988ff878()))
	return swig_r
}

func DeleteStringType(arg1 StringType) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_StringType_pb_d9d2dd81988ff878(C.uintptr_t(_swig_i_0))
}

func (_swig_base SwigcptrStringType) Serialize() (_swig_ret Std_vector_Sl_char_Sg_) {
	var swig_r Std_vector_Sl_char_Sg_
	swig_r = (Std_vector_Sl_char_Sg_)(SwigcptrStd_vector_Sl_char_Sg_(C._wrap_StringType_serialize_pb_d9d2dd81988ff878(C.uintptr_t(_swig_base))))
	return swig_r
}

func StringTypeDeserialize(arg1 Std_vector_Sl_char_Sg_) (_swig_ret Value) {
	var swig_r Value
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (Value)(SwigcptrValue(C._wrap_StringType_deserialize_pb_d9d2dd81988ff878(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (p SwigcptrStringType) SwigIsType() {
}

func (p SwigcptrStringType) SwigGetType() Type {
	return SwigcptrType(getSwigcptr(p))
}

func (p SwigcptrStringType) SwigIsValue() {
}

func (p SwigcptrStringType) SwigGetValue() Value {
	return SwigcptrValue(getSwigcptr(p))
}

type StringType interface {
	Swigcptr() uintptr
	SwigIsStringType()
	Serialize() (_swig_ret Std_vector_Sl_char_Sg_)
	SwigIsType()
	SwigGetType() Type
	SwigIsValue()
	SwigGetValue() Value
}

type SwigcptrTupleType uintptr

func (p SwigcptrTupleType) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrTupleType) SwigIsTupleType() {
}

func (arg1 SwigcptrTupleType) SetElements(arg2 Std_vector_Sl_Type_Sg_) {
	_swig_i_0 := arg1
	_swig_i_1 := getSwigcptr(arg2)
	C._wrap_TupleType_elements_set_pb_d9d2dd81988ff878(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrTupleType) GetElements() (_swig_ret Std_vector_Sl_Type_Sg_) {
	var swig_r Std_vector_Sl_Type_Sg_
	_swig_i_0 := arg1
	swig_r = (Std_vector_Sl_Type_Sg_)(SwigcptrStd_vector_Sl_Type_Sg_(C._wrap_TupleType_elements_get_pb_d9d2dd81988ff878(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewTupleType() (_swig_ret TupleType) {
	var swig_r TupleType
	swig_r = (TupleType)(SwigcptrTupleType(C._wrap_new_TupleType_pb_d9d2dd81988ff878()))
	return swig_r
}

func DeleteTupleType(arg1 TupleType) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_TupleType_pb_d9d2dd81988ff878(C.uintptr_t(_swig_i_0))
}

func (_swig_base SwigcptrTupleType) Serialize() (_swig_ret Std_vector_Sl_char_Sg_) {
	var swig_r Std_vector_Sl_char_Sg_
	swig_r = (Std_vector_Sl_char_Sg_)(SwigcptrStd_vector_Sl_char_Sg_(C._wrap_TupleType_serialize_pb_d9d2dd81988ff878(C.uintptr_t(_swig_base))))
	return swig_r
}

func TupleTypeDeserialize(arg1 Std_vector_Sl_char_Sg_) (_swig_ret Value) {
	var swig_r Value
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (Value)(SwigcptrValue(C._wrap_TupleType_deserialize_pb_d9d2dd81988ff878(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (p SwigcptrTupleType) SwigIsType() {
}

func (p SwigcptrTupleType) SwigGetType() Type {
	return SwigcptrType(getSwigcptr(p))
}

func (p SwigcptrTupleType) SwigIsValue() {
}

func (p SwigcptrTupleType) SwigGetValue() Value {
	return SwigcptrValue(getSwigcptr(p))
}

type TupleType interface {
	Swigcptr() uintptr
	SwigIsTupleType()
	SetElements(arg2 Std_vector_Sl_Type_Sg_)
	GetElements() (_swig_ret Std_vector_Sl_Type_Sg_)
	Serialize() (_swig_ret Std_vector_Sl_char_Sg_)
	SwigIsType()
	SwigGetType() Type
	SwigIsValue()
	SwigGetValue() Value
}

type SwigcptrListType uintptr

func (p SwigcptrListType) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrListType) SwigIsListType() {
}

func (arg1 SwigcptrListType) SetElement(arg2 Type) {
	_swig_i_0 := arg1
	_swig_i_1 := getSwigcptr(arg2)
	C._wrap_ListType_element_set_pb_d9d2dd81988ff878(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrListType) GetElement() (_swig_ret Type) {
	var swig_r Type
	_swig_i_0 := arg1
	swig_r = (Type)(SwigcptrType(C._wrap_ListType_element_get_pb_d9d2dd81988ff878(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewListType() (_swig_ret ListType) {
	var swig_r ListType
	swig_r = (ListType)(SwigcptrListType(C._wrap_new_ListType_pb_d9d2dd81988ff878()))
	return swig_r
}

func DeleteListType(arg1 ListType) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_ListType_pb_d9d2dd81988ff878(C.uintptr_t(_swig_i_0))
}

func (_swig_base SwigcptrListType) Serialize() (_swig_ret Std_vector_Sl_char_Sg_) {
	var swig_r Std_vector_Sl_char_Sg_
	swig_r = (Std_vector_Sl_char_Sg_)(SwigcptrStd_vector_Sl_char_Sg_(C._wrap_ListType_serialize_pb_d9d2dd81988ff878(C.uintptr_t(_swig_base))))
	return swig_r
}

func ListTypeDeserialize(arg1 Std_vector_Sl_char_Sg_) (_swig_ret Value) {
	var swig_r Value
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (Value)(SwigcptrValue(C._wrap_ListType_deserialize_pb_d9d2dd81988ff878(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (p SwigcptrListType) SwigIsType() {
}

func (p SwigcptrListType) SwigGetType() Type {
	return SwigcptrType(getSwigcptr(p))
}

func (p SwigcptrListType) SwigIsValue() {
}

func (p SwigcptrListType) SwigGetValue() Value {
	return SwigcptrValue(getSwigcptr(p))
}

type ListType interface {
	Swigcptr() uintptr
	SwigIsListType()
	SetElement(arg2 Type)
	GetElement() (_swig_ret Type)
	Serialize() (_swig_ret Std_vector_Sl_char_Sg_)
	SwigIsType()
	SwigGetType() Type
	SwigIsValue()
	SwigGetValue() Value
}

type SwigcptrFnType uintptr

func (p SwigcptrFnType) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrFnType) SwigIsFnType() {
}

func (arg1 SwigcptrFnType) SetArgument(arg2 Type) {
	_swig_i_0 := arg1
	_swig_i_1 := getSwigcptr(arg2)
	C._wrap_FnType_argument_set_pb_d9d2dd81988ff878(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrFnType) GetArgument() (_swig_ret Type) {
	var swig_r Type
	_swig_i_0 := arg1
	swig_r = (Type)(SwigcptrType(C._wrap_FnType_argument_get_pb_d9d2dd81988ff878(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrFnType) SetX_return(arg2 Type) {
	_swig_i_0 := arg1
	_swig_i_1 := getSwigcptr(arg2)
	C._wrap_FnType__return_set_pb_d9d2dd81988ff878(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrFnType) GetX_return() (_swig_ret Type) {
	var swig_r Type
	_swig_i_0 := arg1
	swig_r = (Type)(SwigcptrType(C._wrap_FnType__return_get_pb_d9d2dd81988ff878(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewFnType() (_swig_ret FnType) {
	var swig_r FnType
	swig_r = (FnType)(SwigcptrFnType(C._wrap_new_FnType_pb_d9d2dd81988ff878()))
	return swig_r
}

func DeleteFnType(arg1 FnType) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_FnType_pb_d9d2dd81988ff878(C.uintptr_t(_swig_i_0))
}

func (_swig_base SwigcptrFnType) Serialize() (_swig_ret Std_vector_Sl_char_Sg_) {
	var swig_r Std_vector_Sl_char_Sg_
	swig_r = (Std_vector_Sl_char_Sg_)(SwigcptrStd_vector_Sl_char_Sg_(C._wrap_FnType_serialize_pb_d9d2dd81988ff878(C.uintptr_t(_swig_base))))
	return swig_r
}

func FnTypeDeserialize(arg1 Std_vector_Sl_char_Sg_) (_swig_ret Value) {
	var swig_r Value
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (Value)(SwigcptrValue(C._wrap_FnType_deserialize_pb_d9d2dd81988ff878(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (p SwigcptrFnType) SwigIsType() {
}

func (p SwigcptrFnType) SwigGetType() Type {
	return SwigcptrType(getSwigcptr(p))
}

func (p SwigcptrFnType) SwigIsValue() {
}

func (p SwigcptrFnType) SwigGetValue() Value {
	return SwigcptrValue(getSwigcptr(p))
}

type FnType interface {
	Swigcptr() uintptr
	SwigIsFnType()
	SetArgument(arg2 Type)
	GetArgument() (_swig_ret Type)
	SetX_return(arg2 Type)
	GetX_return() (_swig_ret Type)
	Serialize() (_swig_ret Std_vector_Sl_char_Sg_)
	SwigIsType()
	SwigGetType() Type
	SwigIsValue()
	SwigGetValue() Value
}

type SwigcptrStructType uintptr

func (p SwigcptrStructType) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrStructType) SwigIsStructType() {
}

func (arg1 SwigcptrStructType) SetName(arg2 Std_string) {
	_swig_i_0 := arg1
	_swig_i_1 := getSwigcptr(arg2)
	C._wrap_StructType_name_set_pb_d9d2dd81988ff878(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrStructType) GetName() (_swig_ret Std_string) {
	var swig_r Std_string
	_swig_i_0 := arg1
	swig_r = (Std_string)(SwigcptrStd_string(C._wrap_StructType_name_get_pb_d9d2dd81988ff878(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewStructType() (_swig_ret StructType) {
	var swig_r StructType
	swig_r = (StructType)(SwigcptrStructType(C._wrap_new_StructType_pb_d9d2dd81988ff878()))
	return swig_r
}

func DeleteStructType(arg1 StructType) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_StructType_pb_d9d2dd81988ff878(C.uintptr_t(_swig_i_0))
}

func (_swig_base SwigcptrStructType) Serialize() (_swig_ret Std_vector_Sl_char_Sg_) {
	var swig_r Std_vector_Sl_char_Sg_
	swig_r = (Std_vector_Sl_char_Sg_)(SwigcptrStd_vector_Sl_char_Sg_(C._wrap_StructType_serialize_pb_d9d2dd81988ff878(C.uintptr_t(_swig_base))))
	return swig_r
}

func StructTypeDeserialize(arg1 Std_vector_Sl_char_Sg_) (_swig_ret Value) {
	var swig_r Value
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (Value)(SwigcptrValue(C._wrap_StructType_deserialize_pb_d9d2dd81988ff878(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (p SwigcptrStructType) SwigIsType() {
}

func (p SwigcptrStructType) SwigGetType() Type {
	return SwigcptrType(getSwigcptr(p))
}

func (p SwigcptrStructType) SwigIsValue() {
}

func (p SwigcptrStructType) SwigGetValue() Value {
	return SwigcptrValue(getSwigcptr(p))
}

type StructType interface {
	Swigcptr() uintptr
	SwigIsStructType()
	SetName(arg2 Std_string)
	GetName() (_swig_ret Std_string)
	Serialize() (_swig_ret Std_vector_Sl_char_Sg_)
	SwigIsType()
	SwigGetType() Type
	SwigIsValue()
	SwigGetValue() Value
}

type SwigcptrExpression uintptr

func (p SwigcptrExpression) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrExpression) SwigIsExpression() {
}

func NewExpression() (_swig_ret Expression) {
	var swig_r Expression
	swig_r = (Expression)(SwigcptrExpression(C._wrap_new_Expression_pb_d9d2dd81988ff878()))
	return swig_r
}

func DeleteExpression(arg1 Expression) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_Expression_pb_d9d2dd81988ff878(C.uintptr_t(_swig_i_0))
}

func (_swig_base SwigcptrExpression) Serialize() (_swig_ret Std_vector_Sl_char_Sg_) {
	var swig_r Std_vector_Sl_char_Sg_
	swig_r = (Std_vector_Sl_char_Sg_)(SwigcptrStd_vector_Sl_char_Sg_(C._wrap_Expression_serialize_pb_d9d2dd81988ff878(C.uintptr_t(_swig_base))))
	return swig_r
}

func ExpressionDeserialize(arg1 Std_vector_Sl_char_Sg_) (_swig_ret Value) {
	var swig_r Value
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (Value)(SwigcptrValue(C._wrap_Expression_deserialize_pb_d9d2dd81988ff878(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (p SwigcptrExpression) SwigIsValue() {
}

func (p SwigcptrExpression) SwigGetValue() Value {
	return SwigcptrValue(getSwigcptr(p))
}

type Expression interface {
	Swigcptr() uintptr
	SwigIsExpression()
	Serialize() (_swig_ret Std_vector_Sl_char_Sg_)
	SwigIsValue()
	SwigGetValue() Value
}

type SwigcptrString uintptr

func (p SwigcptrString) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrString) SwigIsString() {
}

func (arg1 SwigcptrString) SetValue(arg2 Std_string) {
	_swig_i_0 := arg1
	_swig_i_1 := getSwigcptr(arg2)
	C._wrap_String_value_set_pb_d9d2dd81988ff878(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrString) GetValue() (_swig_ret Std_string) {
	var swig_r Std_string
	_swig_i_0 := arg1
	swig_r = (Std_string)(SwigcptrStd_string(C._wrap_String_value_get_pb_d9d2dd81988ff878(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewString() (_swig_ret String) {
	var swig_r String
	swig_r = (String)(SwigcptrString(C._wrap_new_String_pb_d9d2dd81988ff878()))
	return swig_r
}

func DeleteString(arg1 String) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_String_pb_d9d2dd81988ff878(C.uintptr_t(_swig_i_0))
}

func (_swig_base SwigcptrString) Serialize() (_swig_ret Std_vector_Sl_char_Sg_) {
	var swig_r Std_vector_Sl_char_Sg_
	swig_r = (Std_vector_Sl_char_Sg_)(SwigcptrStd_vector_Sl_char_Sg_(C._wrap_String_serialize_pb_d9d2dd81988ff878(C.uintptr_t(_swig_base))))
	return swig_r
}

func StringDeserialize(arg1 Std_vector_Sl_char_Sg_) (_swig_ret Value) {
	var swig_r Value
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (Value)(SwigcptrValue(C._wrap_String_deserialize_pb_d9d2dd81988ff878(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (p SwigcptrString) SwigIsExpression() {
}

func (p SwigcptrString) SwigGetExpression() Expression {
	return SwigcptrExpression(getSwigcptr(p))
}

func (p SwigcptrString) SwigIsValue() {
}

func (p SwigcptrString) SwigGetValue() Value {
	return SwigcptrValue(getSwigcptr(p))
}

type String interface {
	Swigcptr() uintptr
	SwigIsString()
	SetValue(arg2 Std_string)
	GetValue() (_swig_ret Std_string)
	Serialize() (_swig_ret Std_vector_Sl_char_Sg_)
	SwigIsExpression()
	SwigGetExpression() Expression
	SwigIsValue()
	SwigGetValue() Value
}


type SwigcptrStd_vector_Sl_Type_Sg_ uintptr
type Std_vector_Sl_Type_Sg_ interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStd_vector_Sl_Type_Sg_) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStd_string uintptr
type Std_string interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStd_string) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStd_vector_Sl_char_Sg_ uintptr
type Std_vector_Sl_char_Sg_ interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStd_vector_Sl_char_Sg_) Swigcptr() uintptr {
	return uintptr(p)
}

