/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

// source: pb.swigcxx

package pb

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stddef.h>
#include <stdint.h>


typedef ptrdiff_t intgo;
typedef size_t uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef long long swig_type_1;
typedef long long swig_type_2;
typedef long long swig_type_3;
typedef long long swig_type_4;
typedef long long swig_type_5;
typedef long long swig_type_6;
typedef long long swig_type_7;
typedef long long swig_type_8;
typedef _gostring_ swig_type_9;
typedef _gostring_ swig_type_10;
typedef _gostring_ swig_type_11;
typedef _gostring_ swig_type_12;
typedef _gostring_ swig_type_13;
typedef _gostring_ swig_type_14;
typedef _gostring_ swig_type_15;
extern void _wrap_Swig_free_pb_10c8593e675607f8(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_pb_10c8593e675607f8(swig_intgo arg1);
extern uintptr_t _wrap_new_TypeVector__SWIG_0_pb_10c8593e675607f8(void);
extern uintptr_t _wrap_new_TypeVector__SWIG_1_pb_10c8593e675607f8(swig_type_1 arg1);
extern uintptr_t _wrap_new_TypeVector__SWIG_2_pb_10c8593e675607f8(uintptr_t arg1);
extern swig_type_2 _wrap_TypeVector_size_pb_10c8593e675607f8(uintptr_t arg1);
extern swig_type_3 _wrap_TypeVector_capacity_pb_10c8593e675607f8(uintptr_t arg1);
extern void _wrap_TypeVector_reserve_pb_10c8593e675607f8(uintptr_t arg1, swig_type_4 arg2);
extern _Bool _wrap_TypeVector_isEmpty_pb_10c8593e675607f8(uintptr_t arg1);
extern void _wrap_TypeVector_clear_pb_10c8593e675607f8(uintptr_t arg1);
extern void _wrap_TypeVector_add_pb_10c8593e675607f8(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_TypeVector_get_pb_10c8593e675607f8(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_TypeVector_set_pb_10c8593e675607f8(uintptr_t arg1, swig_intgo arg2, uintptr_t arg3);
extern void _wrap_delete_TypeVector_pb_10c8593e675607f8(uintptr_t arg1);
extern uintptr_t _wrap_new_ValueVector__SWIG_0_pb_10c8593e675607f8(void);
extern uintptr_t _wrap_new_ValueVector__SWIG_1_pb_10c8593e675607f8(swig_type_5 arg1);
extern uintptr_t _wrap_new_ValueVector__SWIG_2_pb_10c8593e675607f8(uintptr_t arg1);
extern swig_type_6 _wrap_ValueVector_size_pb_10c8593e675607f8(uintptr_t arg1);
extern swig_type_7 _wrap_ValueVector_capacity_pb_10c8593e675607f8(uintptr_t arg1);
extern void _wrap_ValueVector_reserve_pb_10c8593e675607f8(uintptr_t arg1, swig_type_8 arg2);
extern _Bool _wrap_ValueVector_isEmpty_pb_10c8593e675607f8(uintptr_t arg1);
extern void _wrap_ValueVector_clear_pb_10c8593e675607f8(uintptr_t arg1);
extern void _wrap_ValueVector_add_pb_10c8593e675607f8(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_ValueVector_get_pb_10c8593e675607f8(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_ValueVector_set_pb_10c8593e675607f8(uintptr_t arg1, swig_intgo arg2, uintptr_t arg3);
extern void _wrap_delete_ValueVector_pb_10c8593e675607f8(uintptr_t arg1);
extern _Bool _wrap_Value_eq_pb_10c8593e675607f8(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_new_Value_pb_10c8593e675607f8(void);
extern void _wrap_delete_Value_pb_10c8593e675607f8(uintptr_t arg1);
extern uintptr_t _wrap_new_Type_pb_10c8593e675607f8(void);
extern void _wrap_delete_Type_pb_10c8593e675607f8(uintptr_t arg1);
extern _Bool _wrap_Type_eq_pb_10c8593e675607f8(uintptr_t _swig_base, uintptr_t arg1);
extern uintptr_t _wrap_new_TypeType_pb_10c8593e675607f8(void);
extern void _wrap_delete_TypeType_pb_10c8593e675607f8(uintptr_t arg1);
extern _Bool _wrap_TypeType_eq_pb_10c8593e675607f8(uintptr_t _swig_base, uintptr_t arg1);
extern uintptr_t _wrap_new_IntType_pb_10c8593e675607f8(void);
extern void _wrap_delete_IntType_pb_10c8593e675607f8(uintptr_t arg1);
extern _Bool _wrap_IntType_eq_pb_10c8593e675607f8(uintptr_t _swig_base, uintptr_t arg1);
extern uintptr_t _wrap_new_FloatType_pb_10c8593e675607f8(void);
extern void _wrap_delete_FloatType_pb_10c8593e675607f8(uintptr_t arg1);
extern _Bool _wrap_FloatType_eq_pb_10c8593e675607f8(uintptr_t _swig_base, uintptr_t arg1);
extern uintptr_t _wrap_new_BoolType_pb_10c8593e675607f8(void);
extern void _wrap_delete_BoolType_pb_10c8593e675607f8(uintptr_t arg1);
extern _Bool _wrap_BoolType_eq_pb_10c8593e675607f8(uintptr_t _swig_base, uintptr_t arg1);
extern uintptr_t _wrap_new_StringType_pb_10c8593e675607f8(void);
extern void _wrap_delete_StringType_pb_10c8593e675607f8(uintptr_t arg1);
extern _Bool _wrap_StringType_eq_pb_10c8593e675607f8(uintptr_t _swig_base, uintptr_t arg1);
extern uintptr_t _wrap_new_NilType_pb_10c8593e675607f8(void);
extern void _wrap_delete_NilType_pb_10c8593e675607f8(uintptr_t arg1);
extern _Bool _wrap_NilType_eq_pb_10c8593e675607f8(uintptr_t _swig_base, uintptr_t arg1);
extern uintptr_t _wrap_new_TupleType_pb_10c8593e675607f8(uintptr_t arg1);
extern void _wrap_TupleType_elements_set_pb_10c8593e675607f8(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_TupleType_elements_get_pb_10c8593e675607f8(uintptr_t arg1);
extern void _wrap_delete_TupleType_pb_10c8593e675607f8(uintptr_t arg1);
extern _Bool _wrap_TupleType_eq_pb_10c8593e675607f8(uintptr_t _swig_base, uintptr_t arg1);
extern uintptr_t _wrap_new_ListType_pb_10c8593e675607f8(uintptr_t arg1);
extern void _wrap_ListType_element_set_pb_10c8593e675607f8(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_ListType_element_get_pb_10c8593e675607f8(uintptr_t arg1);
extern void _wrap_delete_ListType_pb_10c8593e675607f8(uintptr_t arg1);
extern _Bool _wrap_ListType_eq_pb_10c8593e675607f8(uintptr_t _swig_base, uintptr_t arg1);
extern uintptr_t _wrap_new_FnType_pb_10c8593e675607f8(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_FnType_argument_set_pb_10c8593e675607f8(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_FnType_argument_get_pb_10c8593e675607f8(uintptr_t arg1);
extern void _wrap_FnType_returnType_set_pb_10c8593e675607f8(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_FnType_returnType_get_pb_10c8593e675607f8(uintptr_t arg1);
extern void _wrap_delete_FnType_pb_10c8593e675607f8(uintptr_t arg1);
extern _Bool _wrap_FnType_eq_pb_10c8593e675607f8(uintptr_t _swig_base, uintptr_t arg1);
extern uintptr_t _wrap_new_StructType_pb_10c8593e675607f8(swig_type_9 arg1);
extern void _wrap_StructType_name_set_pb_10c8593e675607f8(uintptr_t arg1, swig_type_10 arg2);
extern swig_type_11 _wrap_StructType_name_get_pb_10c8593e675607f8(uintptr_t arg1);
extern void _wrap_delete_StructType_pb_10c8593e675607f8(uintptr_t arg1);
extern _Bool _wrap_StructType_eq_pb_10c8593e675607f8(uintptr_t _swig_base, uintptr_t arg1);
extern uintptr_t _wrap_new_Expression_pb_10c8593e675607f8(void);
extern void _wrap_delete_Expression_pb_10c8593e675607f8(uintptr_t arg1);
extern _Bool _wrap_Expression_eq_pb_10c8593e675607f8(uintptr_t _swig_base, uintptr_t arg1);
extern void _wrap_String_value_set_pb_10c8593e675607f8(uintptr_t arg1, swig_type_12 arg2);
extern swig_type_13 _wrap_String_value_get_pb_10c8593e675607f8(uintptr_t arg1);
extern uintptr_t _wrap_new_String_pb_10c8593e675607f8(void);
extern void _wrap_delete_String_pb_10c8593e675607f8(uintptr_t arg1);
extern _Bool _wrap_String_eq_pb_10c8593e675607f8(uintptr_t _swig_base, uintptr_t arg1);
extern swig_type_14 _wrap_serializeValues_pb_10c8593e675607f8(uintptr_t arg1);
extern uintptr_t _wrap_deserializeValues_pb_10c8593e675607f8(swig_type_15 arg1);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


func getSwigcptr(v interface { Swigcptr() uintptr }) uintptr {
	if v == nil {
		return 0
	}
	return v.Swigcptr()
}


type _ sync.Mutex

//export cgo_panic__pb_10c8593e675607f8
func cgo_panic__pb_10c8593e675607f8(p *byte) {
	s := (*[1024]byte)(unsafe.Pointer(p))[:]
	for i, b := range s {
		if b == 0 {
			panic(string(s[:i]))
		}
	}
	panic(string(s))
}


type swig_gostring struct { p uintptr; n int }
func swigCopyString(s string) string {
  p := *(*swig_gostring)(unsafe.Pointer(&s))
  r := string((*[0x7fffffff]byte)(unsafe.Pointer(p.p))[:p.n])
  Swig_free(p.p)
  return r
}

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_pb_10c8593e675607f8(C.swig_intgo(_swig_i_0)))
	return swig_r
}

type SwigcptrTypeVector uintptr

func (p SwigcptrTypeVector) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrTypeVector) SwigIsTypeVector() {
}

func NewTypeVector__SWIG_0() (_swig_ret TypeVector) {
	var swig_r TypeVector
	swig_r = (TypeVector)(SwigcptrTypeVector(C._wrap_new_TypeVector__SWIG_0_pb_10c8593e675607f8()))
	return swig_r
}

func NewTypeVector__SWIG_1(arg1 int64) (_swig_ret TypeVector) {
	var swig_r TypeVector
	_swig_i_0 := arg1
	swig_r = (TypeVector)(SwigcptrTypeVector(C._wrap_new_TypeVector__SWIG_1_pb_10c8593e675607f8(C.swig_type_1(_swig_i_0))))
	return swig_r
}

func NewTypeVector__SWIG_2(arg1 TypeVector) (_swig_ret TypeVector) {
	var swig_r TypeVector
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (TypeVector)(SwigcptrTypeVector(C._wrap_new_TypeVector__SWIG_2_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewTypeVector(a ...interface{}) TypeVector {
	argc := len(a)
	if argc == 0 {
		return NewTypeVector__SWIG_0()
	}
	if argc == 1 {
		if _, ok := a[0].(int64); !ok {
			goto check_2
		}
		return NewTypeVector__SWIG_1(a[0].(int64))
	}
check_2:
	if argc == 1 {
		return NewTypeVector__SWIG_2(a[0].(TypeVector))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrTypeVector) Size() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_TypeVector_size_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrTypeVector) Capacity() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_TypeVector_capacity_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrTypeVector) Reserve(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_TypeVector_reserve_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0), C.swig_type_4(_swig_i_1))
}

func (arg1 SwigcptrTypeVector) IsEmpty() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_TypeVector_isEmpty_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrTypeVector) Clear() {
	_swig_i_0 := arg1
	C._wrap_TypeVector_clear_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrTypeVector) Add(arg2 Type) {
	_swig_i_0 := arg1
	_swig_i_1 := getSwigcptr(arg2)
	C._wrap_TypeVector_add_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrTypeVector) Get(arg2 int) (_swig_ret Type) {
	var swig_r Type
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (Type)(SwigcptrType(C._wrap_TypeVector_get_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))))
	return swig_r
}

func (arg1 SwigcptrTypeVector) Set(arg2 int, arg3 Type) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := getSwigcptr(arg3)
	C._wrap_TypeVector_set_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), C.uintptr_t(_swig_i_2))
}

func DeleteTypeVector(arg1 TypeVector) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_TypeVector_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0))
}

type TypeVector interface {
	Swigcptr() uintptr
	SwigIsTypeVector()
	Size() (_swig_ret int64)
	Capacity() (_swig_ret int64)
	Reserve(arg2 int64)
	IsEmpty() (_swig_ret bool)
	Clear()
	Add(arg2 Type)
	Get(arg2 int) (_swig_ret Type)
	Set(arg2 int, arg3 Type)
}

type SwigcptrValueVector uintptr

func (p SwigcptrValueVector) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrValueVector) SwigIsValueVector() {
}

func NewValueVector__SWIG_0() (_swig_ret ValueVector) {
	var swig_r ValueVector
	swig_r = (ValueVector)(SwigcptrValueVector(C._wrap_new_ValueVector__SWIG_0_pb_10c8593e675607f8()))
	return swig_r
}

func NewValueVector__SWIG_1(arg1 int64) (_swig_ret ValueVector) {
	var swig_r ValueVector
	_swig_i_0 := arg1
	swig_r = (ValueVector)(SwigcptrValueVector(C._wrap_new_ValueVector__SWIG_1_pb_10c8593e675607f8(C.swig_type_5(_swig_i_0))))
	return swig_r
}

func NewValueVector__SWIG_2(arg1 ValueVector) (_swig_ret ValueVector) {
	var swig_r ValueVector
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (ValueVector)(SwigcptrValueVector(C._wrap_new_ValueVector__SWIG_2_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewValueVector(a ...interface{}) ValueVector {
	argc := len(a)
	if argc == 0 {
		return NewValueVector__SWIG_0()
	}
	if argc == 1 {
		if _, ok := a[0].(int64); !ok {
			goto check_2
		}
		return NewValueVector__SWIG_1(a[0].(int64))
	}
check_2:
	if argc == 1 {
		return NewValueVector__SWIG_2(a[0].(ValueVector))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrValueVector) Size() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_ValueVector_size_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrValueVector) Capacity() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_ValueVector_capacity_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrValueVector) Reserve(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_ValueVector_reserve_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0), C.swig_type_8(_swig_i_1))
}

func (arg1 SwigcptrValueVector) IsEmpty() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_ValueVector_isEmpty_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrValueVector) Clear() {
	_swig_i_0 := arg1
	C._wrap_ValueVector_clear_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrValueVector) Add(arg2 Value) {
	_swig_i_0 := arg1
	_swig_i_1 := getSwigcptr(arg2)
	C._wrap_ValueVector_add_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrValueVector) Get(arg2 int) (_swig_ret Value) {
	var swig_r Value
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (Value)(SwigcptrValue(C._wrap_ValueVector_get_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))))
	return swig_r
}

func (arg1 SwigcptrValueVector) Set(arg2 int, arg3 Value) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := getSwigcptr(arg3)
	C._wrap_ValueVector_set_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), C.uintptr_t(_swig_i_2))
}

func DeleteValueVector(arg1 ValueVector) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_ValueVector_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0))
}

type ValueVector interface {
	Swigcptr() uintptr
	SwigIsValueVector()
	Size() (_swig_ret int64)
	Capacity() (_swig_ret int64)
	Reserve(arg2 int64)
	IsEmpty() (_swig_ret bool)
	Clear()
	Add(arg2 Value)
	Get(arg2 int) (_swig_ret Value)
	Set(arg2 int, arg3 Value)
}

type SwigcptrValue uintptr

func (p SwigcptrValue) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrValue) SwigIsValue() {
}

func (arg1 SwigcptrValue) Eq(arg2 Value) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	_swig_i_1 := getSwigcptr(arg2)
	swig_r = (bool)(C._wrap_Value_eq_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func NewValue() (_swig_ret Value) {
	var swig_r Value
	swig_r = (Value)(SwigcptrValue(C._wrap_new_Value_pb_10c8593e675607f8()))
	return swig_r
}

func DeleteValue(arg1 Value) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_Value_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0))
}

type Value interface {
	Swigcptr() uintptr
	SwigIsValue()
	Eq(arg2 Value) (_swig_ret bool)
}

type SwigcptrType uintptr

func (p SwigcptrType) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrType) SwigIsType() {
}

func NewType() (_swig_ret Type) {
	var swig_r Type
	swig_r = (Type)(SwigcptrType(C._wrap_new_Type_pb_10c8593e675607f8()))
	return swig_r
}

func DeleteType(arg1 Type) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_Type_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0))
}

func (_swig_base SwigcptrType) Eq(arg1 Value) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (bool)(C._wrap_Type_eq_pb_10c8593e675607f8(C.uintptr_t(_swig_base), C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (p SwigcptrType) SwigIsValue() {
}

func (p SwigcptrType) SwigGetValue() Value {
	return SwigcptrValue(getSwigcptr(p))
}

type Type interface {
	Swigcptr() uintptr
	SwigIsType()
	Eq(arg1 Value) (_swig_ret bool)
	SwigIsValue()
	SwigGetValue() Value
}

type SwigcptrTypeType uintptr

func (p SwigcptrTypeType) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrTypeType) SwigIsTypeType() {
}

func NewTypeType() (_swig_ret TypeType) {
	var swig_r TypeType
	swig_r = (TypeType)(SwigcptrTypeType(C._wrap_new_TypeType_pb_10c8593e675607f8()))
	return swig_r
}

func DeleteTypeType(arg1 TypeType) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_TypeType_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0))
}

func (_swig_base SwigcptrTypeType) Eq(arg1 Value) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (bool)(C._wrap_TypeType_eq_pb_10c8593e675607f8(C.uintptr_t(_swig_base), C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (p SwigcptrTypeType) SwigIsType() {
}

func (p SwigcptrTypeType) SwigGetType() Type {
	return SwigcptrType(getSwigcptr(p))
}

func (p SwigcptrTypeType) SwigIsValue() {
}

func (p SwigcptrTypeType) SwigGetValue() Value {
	return SwigcptrValue(getSwigcptr(p))
}

type TypeType interface {
	Swigcptr() uintptr
	SwigIsTypeType()
	Eq(arg1 Value) (_swig_ret bool)
	SwigIsType()
	SwigGetType() Type
	SwigIsValue()
	SwigGetValue() Value
}

type SwigcptrIntType uintptr

func (p SwigcptrIntType) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrIntType) SwigIsIntType() {
}

func NewIntType() (_swig_ret IntType) {
	var swig_r IntType
	swig_r = (IntType)(SwigcptrIntType(C._wrap_new_IntType_pb_10c8593e675607f8()))
	return swig_r
}

func DeleteIntType(arg1 IntType) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_IntType_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0))
}

func (_swig_base SwigcptrIntType) Eq(arg1 Value) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (bool)(C._wrap_IntType_eq_pb_10c8593e675607f8(C.uintptr_t(_swig_base), C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (p SwigcptrIntType) SwigIsType() {
}

func (p SwigcptrIntType) SwigGetType() Type {
	return SwigcptrType(getSwigcptr(p))
}

func (p SwigcptrIntType) SwigIsValue() {
}

func (p SwigcptrIntType) SwigGetValue() Value {
	return SwigcptrValue(getSwigcptr(p))
}

type IntType interface {
	Swigcptr() uintptr
	SwigIsIntType()
	Eq(arg1 Value) (_swig_ret bool)
	SwigIsType()
	SwigGetType() Type
	SwigIsValue()
	SwigGetValue() Value
}

type SwigcptrFloatType uintptr

func (p SwigcptrFloatType) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrFloatType) SwigIsFloatType() {
}

func NewFloatType() (_swig_ret FloatType) {
	var swig_r FloatType
	swig_r = (FloatType)(SwigcptrFloatType(C._wrap_new_FloatType_pb_10c8593e675607f8()))
	return swig_r
}

func DeleteFloatType(arg1 FloatType) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_FloatType_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0))
}

func (_swig_base SwigcptrFloatType) Eq(arg1 Value) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (bool)(C._wrap_FloatType_eq_pb_10c8593e675607f8(C.uintptr_t(_swig_base), C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (p SwigcptrFloatType) SwigIsType() {
}

func (p SwigcptrFloatType) SwigGetType() Type {
	return SwigcptrType(getSwigcptr(p))
}

func (p SwigcptrFloatType) SwigIsValue() {
}

func (p SwigcptrFloatType) SwigGetValue() Value {
	return SwigcptrValue(getSwigcptr(p))
}

type FloatType interface {
	Swigcptr() uintptr
	SwigIsFloatType()
	Eq(arg1 Value) (_swig_ret bool)
	SwigIsType()
	SwigGetType() Type
	SwigIsValue()
	SwigGetValue() Value
}

type SwigcptrBoolType uintptr

func (p SwigcptrBoolType) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrBoolType) SwigIsBoolType() {
}

func NewBoolType() (_swig_ret BoolType) {
	var swig_r BoolType
	swig_r = (BoolType)(SwigcptrBoolType(C._wrap_new_BoolType_pb_10c8593e675607f8()))
	return swig_r
}

func DeleteBoolType(arg1 BoolType) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_BoolType_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0))
}

func (_swig_base SwigcptrBoolType) Eq(arg1 Value) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (bool)(C._wrap_BoolType_eq_pb_10c8593e675607f8(C.uintptr_t(_swig_base), C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (p SwigcptrBoolType) SwigIsType() {
}

func (p SwigcptrBoolType) SwigGetType() Type {
	return SwigcptrType(getSwigcptr(p))
}

func (p SwigcptrBoolType) SwigIsValue() {
}

func (p SwigcptrBoolType) SwigGetValue() Value {
	return SwigcptrValue(getSwigcptr(p))
}

type BoolType interface {
	Swigcptr() uintptr
	SwigIsBoolType()
	Eq(arg1 Value) (_swig_ret bool)
	SwigIsType()
	SwigGetType() Type
	SwigIsValue()
	SwigGetValue() Value
}

type SwigcptrStringType uintptr

func (p SwigcptrStringType) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrStringType) SwigIsStringType() {
}

func NewStringType() (_swig_ret StringType) {
	var swig_r StringType
	swig_r = (StringType)(SwigcptrStringType(C._wrap_new_StringType_pb_10c8593e675607f8()))
	return swig_r
}

func DeleteStringType(arg1 StringType) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_StringType_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0))
}

func (_swig_base SwigcptrStringType) Eq(arg1 Value) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (bool)(C._wrap_StringType_eq_pb_10c8593e675607f8(C.uintptr_t(_swig_base), C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (p SwigcptrStringType) SwigIsType() {
}

func (p SwigcptrStringType) SwigGetType() Type {
	return SwigcptrType(getSwigcptr(p))
}

func (p SwigcptrStringType) SwigIsValue() {
}

func (p SwigcptrStringType) SwigGetValue() Value {
	return SwigcptrValue(getSwigcptr(p))
}

type StringType interface {
	Swigcptr() uintptr
	SwigIsStringType()
	Eq(arg1 Value) (_swig_ret bool)
	SwigIsType()
	SwigGetType() Type
	SwigIsValue()
	SwigGetValue() Value
}

type SwigcptrNilType uintptr

func (p SwigcptrNilType) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrNilType) SwigIsNilType() {
}

func NewNilType() (_swig_ret NilType) {
	var swig_r NilType
	swig_r = (NilType)(SwigcptrNilType(C._wrap_new_NilType_pb_10c8593e675607f8()))
	return swig_r
}

func DeleteNilType(arg1 NilType) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_NilType_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0))
}

func (_swig_base SwigcptrNilType) Eq(arg1 Value) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (bool)(C._wrap_NilType_eq_pb_10c8593e675607f8(C.uintptr_t(_swig_base), C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (p SwigcptrNilType) SwigIsType() {
}

func (p SwigcptrNilType) SwigGetType() Type {
	return SwigcptrType(getSwigcptr(p))
}

func (p SwigcptrNilType) SwigIsValue() {
}

func (p SwigcptrNilType) SwigGetValue() Value {
	return SwigcptrValue(getSwigcptr(p))
}

type NilType interface {
	Swigcptr() uintptr
	SwigIsNilType()
	Eq(arg1 Value) (_swig_ret bool)
	SwigIsType()
	SwigGetType() Type
	SwigIsValue()
	SwigGetValue() Value
}

type SwigcptrTupleType uintptr

func (p SwigcptrTupleType) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrTupleType) SwigIsTupleType() {
}

func NewTupleType(arg1 TypeVector) (_swig_ret TupleType) {
	var swig_r TupleType
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (TupleType)(SwigcptrTupleType(C._wrap_new_TupleType_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrTupleType) SetElements(arg2 TypeVector) {
	_swig_i_0 := arg1
	_swig_i_1 := getSwigcptr(arg2)
	C._wrap_TupleType_elements_set_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrTupleType) GetElements() (_swig_ret TypeVector) {
	var swig_r TypeVector
	_swig_i_0 := arg1
	swig_r = (TypeVector)(SwigcptrTypeVector(C._wrap_TupleType_elements_get_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func DeleteTupleType(arg1 TupleType) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_TupleType_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0))
}

func (_swig_base SwigcptrTupleType) Eq(arg1 Value) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (bool)(C._wrap_TupleType_eq_pb_10c8593e675607f8(C.uintptr_t(_swig_base), C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (p SwigcptrTupleType) SwigIsType() {
}

func (p SwigcptrTupleType) SwigGetType() Type {
	return SwigcptrType(getSwigcptr(p))
}

func (p SwigcptrTupleType) SwigIsValue() {
}

func (p SwigcptrTupleType) SwigGetValue() Value {
	return SwigcptrValue(getSwigcptr(p))
}

type TupleType interface {
	Swigcptr() uintptr
	SwigIsTupleType()
	SetElements(arg2 TypeVector)
	GetElements() (_swig_ret TypeVector)
	Eq(arg1 Value) (_swig_ret bool)
	SwigIsType()
	SwigGetType() Type
	SwigIsValue()
	SwigGetValue() Value
}

type SwigcptrListType uintptr

func (p SwigcptrListType) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrListType) SwigIsListType() {
}

func NewListType(arg1 Type) (_swig_ret ListType) {
	var swig_r ListType
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (ListType)(SwigcptrListType(C._wrap_new_ListType_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrListType) SetElement(arg2 Type) {
	_swig_i_0 := arg1
	_swig_i_1 := getSwigcptr(arg2)
	C._wrap_ListType_element_set_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrListType) GetElement() (_swig_ret Type) {
	var swig_r Type
	_swig_i_0 := arg1
	swig_r = (Type)(SwigcptrType(C._wrap_ListType_element_get_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func DeleteListType(arg1 ListType) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_ListType_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0))
}

func (_swig_base SwigcptrListType) Eq(arg1 Value) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (bool)(C._wrap_ListType_eq_pb_10c8593e675607f8(C.uintptr_t(_swig_base), C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (p SwigcptrListType) SwigIsType() {
}

func (p SwigcptrListType) SwigGetType() Type {
	return SwigcptrType(getSwigcptr(p))
}

func (p SwigcptrListType) SwigIsValue() {
}

func (p SwigcptrListType) SwigGetValue() Value {
	return SwigcptrValue(getSwigcptr(p))
}

type ListType interface {
	Swigcptr() uintptr
	SwigIsListType()
	SetElement(arg2 Type)
	GetElement() (_swig_ret Type)
	Eq(arg1 Value) (_swig_ret bool)
	SwigIsType()
	SwigGetType() Type
	SwigIsValue()
	SwigGetValue() Value
}

type SwigcptrFnType uintptr

func (p SwigcptrFnType) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrFnType) SwigIsFnType() {
}

func NewFnType(arg1 Type, arg2 Type) (_swig_ret FnType) {
	var swig_r FnType
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	swig_r = (FnType)(SwigcptrFnType(C._wrap_new_FnType_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func (arg1 SwigcptrFnType) SetArgument(arg2 Type) {
	_swig_i_0 := arg1
	_swig_i_1 := getSwigcptr(arg2)
	C._wrap_FnType_argument_set_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrFnType) GetArgument() (_swig_ret Type) {
	var swig_r Type
	_swig_i_0 := arg1
	swig_r = (Type)(SwigcptrType(C._wrap_FnType_argument_get_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrFnType) SetReturnType(arg2 Type) {
	_swig_i_0 := arg1
	_swig_i_1 := getSwigcptr(arg2)
	C._wrap_FnType_returnType_set_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrFnType) GetReturnType() (_swig_ret Type) {
	var swig_r Type
	_swig_i_0 := arg1
	swig_r = (Type)(SwigcptrType(C._wrap_FnType_returnType_get_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func DeleteFnType(arg1 FnType) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_FnType_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0))
}

func (_swig_base SwigcptrFnType) Eq(arg1 Value) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (bool)(C._wrap_FnType_eq_pb_10c8593e675607f8(C.uintptr_t(_swig_base), C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (p SwigcptrFnType) SwigIsType() {
}

func (p SwigcptrFnType) SwigGetType() Type {
	return SwigcptrType(getSwigcptr(p))
}

func (p SwigcptrFnType) SwigIsValue() {
}

func (p SwigcptrFnType) SwigGetValue() Value {
	return SwigcptrValue(getSwigcptr(p))
}

type FnType interface {
	Swigcptr() uintptr
	SwigIsFnType()
	SetArgument(arg2 Type)
	GetArgument() (_swig_ret Type)
	SetReturnType(arg2 Type)
	GetReturnType() (_swig_ret Type)
	Eq(arg1 Value) (_swig_ret bool)
	SwigIsType()
	SwigGetType() Type
	SwigIsValue()
	SwigGetValue() Value
}

type SwigcptrStructType uintptr

func (p SwigcptrStructType) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrStructType) SwigIsStructType() {
}

func NewStructType(arg1 string) (_swig_ret StructType) {
	var swig_r StructType
	_swig_i_0 := arg1
	swig_r = (StructType)(SwigcptrStructType(C._wrap_new_StructType_pb_10c8593e675607f8(*(*C.swig_type_9)(unsafe.Pointer(&_swig_i_0)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func (arg1 SwigcptrStructType) SetName(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_StructType_name_set_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0), *(*C.swig_type_10)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrStructType) GetName() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_StructType_name_get_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func DeleteStructType(arg1 StructType) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_StructType_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0))
}

func (_swig_base SwigcptrStructType) Eq(arg1 Value) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (bool)(C._wrap_StructType_eq_pb_10c8593e675607f8(C.uintptr_t(_swig_base), C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (p SwigcptrStructType) SwigIsType() {
}

func (p SwigcptrStructType) SwigGetType() Type {
	return SwigcptrType(getSwigcptr(p))
}

func (p SwigcptrStructType) SwigIsValue() {
}

func (p SwigcptrStructType) SwigGetValue() Value {
	return SwigcptrValue(getSwigcptr(p))
}

type StructType interface {
	Swigcptr() uintptr
	SwigIsStructType()
	SetName(arg2 string)
	GetName() (_swig_ret string)
	Eq(arg1 Value) (_swig_ret bool)
	SwigIsType()
	SwigGetType() Type
	SwigIsValue()
	SwigGetValue() Value
}

type SwigcptrExpression uintptr

func (p SwigcptrExpression) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrExpression) SwigIsExpression() {
}

func NewExpression() (_swig_ret Expression) {
	var swig_r Expression
	swig_r = (Expression)(SwigcptrExpression(C._wrap_new_Expression_pb_10c8593e675607f8()))
	return swig_r
}

func DeleteExpression(arg1 Expression) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_Expression_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0))
}

func (_swig_base SwigcptrExpression) Eq(arg1 Value) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (bool)(C._wrap_Expression_eq_pb_10c8593e675607f8(C.uintptr_t(_swig_base), C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (p SwigcptrExpression) SwigIsValue() {
}

func (p SwigcptrExpression) SwigGetValue() Value {
	return SwigcptrValue(getSwigcptr(p))
}

type Expression interface {
	Swigcptr() uintptr
	SwigIsExpression()
	Eq(arg1 Value) (_swig_ret bool)
	SwigIsValue()
	SwigGetValue() Value
}

type SwigcptrString uintptr

func (p SwigcptrString) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrString) SwigIsString() {
}

func (arg1 SwigcptrString) SetValue(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_String_value_set_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0), *(*C.swig_type_12)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrString) GetValue() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_String_value_get_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func NewString() (_swig_ret String) {
	var swig_r String
	swig_r = (String)(SwigcptrString(C._wrap_new_String_pb_10c8593e675607f8()))
	return swig_r
}

func DeleteString(arg1 String) {
	_swig_i_0 := getSwigcptr(arg1)
	C._wrap_delete_String_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0))
}

func (_swig_base SwigcptrString) Eq(arg1 Value) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := getSwigcptr(arg1)
	swig_r = (bool)(C._wrap_String_eq_pb_10c8593e675607f8(C.uintptr_t(_swig_base), C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (p SwigcptrString) SwigIsExpression() {
}

func (p SwigcptrString) SwigGetExpression() Expression {
	return SwigcptrExpression(getSwigcptr(p))
}

func (p SwigcptrString) SwigIsValue() {
}

func (p SwigcptrString) SwigGetValue() Value {
	return SwigcptrValue(getSwigcptr(p))
}

type String interface {
	Swigcptr() uintptr
	SwigIsString()
	SetValue(arg2 string)
	GetValue() (_swig_ret string)
	Eq(arg1 Value) (_swig_ret bool)
	SwigIsExpression()
	SwigGetExpression() Expression
	SwigIsValue()
	SwigGetValue() Value
}

func SerializeValues(arg1 ValueVector) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := getSwigcptr(arg1)
	swig_r_p := C._wrap_serializeValues_pb_10c8593e675607f8(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func DeserializeValues(arg1 string) (_swig_ret ValueVector) {
	var swig_r ValueVector
	_swig_i_0 := arg1
	swig_r = (ValueVector)(SwigcptrValueVector(C._wrap_deserializeValues_pb_10c8593e675607f8(*(*C.swig_type_15)(unsafe.Pointer(&_swig_i_0)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}


