/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

/* source: swig.i */


extern
#ifdef __cplusplus
  "C"
#endif
  void cgo_panic__yune_d3d94ab19c12351a(const char*);
static void _swig_gopanic(const char *p) {
  cgo_panic__yune_d3d94ab19c12351a(p);
}



#define SWIG_VERSION 0x040301
#define SWIGGO
#define SWIGMODULE yune
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif

#if defined(__cplusplus) && __cplusplus >=201103L
# define SWIG_NULLPTR nullptr
#else
# define SWIG_NULLPTR NULL
#endif 

/* -----------------------------------------------------------------------------
 * swigcompat.swg
 *
 * Macros to provide support compatibility with older C and C++ standards.
 *
 * Note that SWIG expects __cplusplus to be defined to the appropriate C++ standard.
 * MSVC users are urged to check and examine the /Zc:__cplusplus compiler option.
 * See https://learn.microsoft.com/en-us/cpp/build/reference/zc-cplusplus.
 * ----------------------------------------------------------------------------- */

/* C99 and C++11 should provide snprintf, but define SWIG_NO_SNPRINTF
 * if you're missing it.
 */
#if ((defined __STDC_VERSION__ && __STDC_VERSION__ >= 199901L) || \
     (defined __cplusplus && __cplusplus >= 201103L) || \
     defined SWIG_HAVE_SNPRINTF) && \
    !defined SWIG_NO_SNPRINTF
# define SWIG_snprintf(O,S,F,A) snprintf(O,S,F,A)
# define SWIG_snprintf2(O,S,F,A,B) snprintf(O,S,F,A,B)
#else
/* Fallback versions ignore the buffer size, but most of our uses either have a
 * fixed maximum possible size or dynamically allocate a buffer that's large
 * enough.
 */
# define SWIG_snprintf(O,S,F,A) sprintf(O,F,A)
# define SWIG_snprintf2(O,S,F,A,B) sprintf(O,F,A,B)
#endif


#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>



typedef ptrdiff_t intgo;
typedef size_t uintgo;


# if !defined(__clang__) && (defined(__i386__) || defined(__x86_64__))
#   define SWIGSTRUCTPACKED __attribute__((__packed__, __gcc_struct__))
# else
#   define SWIGSTRUCTPACKED __attribute__((__packed__))
# endif



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;



static void Swig_free(void* p) {
  free(p);
}

static void* Swig_malloc(int c) {
  return malloc(c);
}


#include "schema.hpp"

#ifdef __cplusplus
extern "C" {
#endif

void _wrap_Swig_free_yune_d3d94ab19c12351a(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  Swig_free(arg1);
  
}


void *_wrap_Swig_malloc_yune_d3d94ab19c12351a(intgo _swig_go_0) {
  int arg1 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (void *)Swig_malloc(arg1);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


std::vector< char > *_wrap_Value_serialize_yune_d3d94ab19c12351a(struct Value *_swig_go_0) {
  struct Value *arg1 = (struct Value *) 0 ;
  std::vector< char > result;
  std::vector< char > *_swig_go_result;
  
  arg1 = *(struct Value **)&_swig_go_0; 
  
  result = (arg1)->serialize();
  {
    std::vector< char > * resultptr = (std::vector< char > *)malloc(sizeof(std::vector< char >));
    memmove(resultptr, &result, sizeof(std::vector< char >));
    *(std::vector< char > **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


Value *_wrap_Value_deserialize_yune_d3d94ab19c12351a(std::vector< char > *_swig_go_0) {
  std::vector< char > arg1 ;
  std::vector< char > *argp1 ;
  Value result;
  Value *_swig_go_result;
  
  
  argp1 = (std::vector< char > *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null std::vector< char >");
  }
  arg1 = (std::vector< char >)*argp1;
  
  
  result = Value::deserialize(arg1);
  {
    Value * resultptr = (Value *)malloc(sizeof(Value));
    memmove(resultptr, &result, sizeof(Value));
    *(Value **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


struct Value *_wrap_new_Value_yune_d3d94ab19c12351a() {
  struct Value *result = 0 ;
  struct Value *_swig_go_result;
  
  
  result = (struct Value *)calloc(1, sizeof(struct Value));
  *(struct Value **)&_swig_go_result = (struct Value *)result; 
  return _swig_go_result;
}


void _wrap_delete_Value_yune_d3d94ab19c12351a(struct Value *_swig_go_0) {
  struct Value *arg1 = (struct Value *) 0 ;
  
  arg1 = *(struct Value **)&_swig_go_0; 
  
  free((char *) arg1);
  
}


struct Type *_wrap_new_Type_yune_d3d94ab19c12351a() {
  struct Type *result = 0 ;
  struct Type *_swig_go_result;
  
  
  result = (struct Type *)calloc(1, sizeof(struct Type));
  *(struct Type **)&_swig_go_result = (struct Type *)result; 
  return _swig_go_result;
}


void _wrap_delete_Type_yune_d3d94ab19c12351a(struct Type *_swig_go_0) {
  struct Type *arg1 = (struct Type *) 0 ;
  
  arg1 = *(struct Type **)&_swig_go_0; 
  
  free((char *) arg1);
  
}


std::vector< char > *_wrap_Type_serialize_yune_d3d94ab19c12351a(struct Type *_swig_go_0) {
  struct Type *arg1 = (struct Type *) 0 ;
  std::vector< char > result;
  std::vector< char > *_swig_go_result;
  
  arg1 = *(struct Type **)&_swig_go_0; 
  
  struct Value *swig_b0 = (struct Value *)arg1;
  result = (swig_b0)->serialize();
  {
    std::vector< char > * resultptr = (std::vector< char > *)malloc(sizeof(std::vector< char >));
    memmove(resultptr, &result, sizeof(std::vector< char >));
    *(std::vector< char > **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


Value *_wrap_Type_deserialize_yune_d3d94ab19c12351a(std::vector< char > *_swig_go_0) {
  std::vector< char > arg1 ;
  std::vector< char > *argp1 ;
  Value result;
  Value *_swig_go_result;
  
  
  argp1 = (std::vector< char > *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null std::vector< char >");
  }
  arg1 = (std::vector< char >)*argp1;
  
  
  result = Value::deserialize(arg1);
  {
    Value * resultptr = (Value *)malloc(sizeof(Value));
    memmove(resultptr, &result, sizeof(Value));
    *(Value **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


struct IntType *_wrap_new_IntType_yune_d3d94ab19c12351a() {
  struct IntType *result = 0 ;
  struct IntType *_swig_go_result;
  
  
  result = (struct IntType *)calloc(1, sizeof(struct IntType));
  *(struct IntType **)&_swig_go_result = (struct IntType *)result; 
  return _swig_go_result;
}


void _wrap_delete_IntType_yune_d3d94ab19c12351a(struct IntType *_swig_go_0) {
  struct IntType *arg1 = (struct IntType *) 0 ;
  
  arg1 = *(struct IntType **)&_swig_go_0; 
  
  free((char *) arg1);
  
}


std::vector< char > *_wrap_IntType_serialize_yune_d3d94ab19c12351a(struct IntType *_swig_go_0) {
  struct IntType *arg1 = (struct IntType *) 0 ;
  std::vector< char > result;
  std::vector< char > *_swig_go_result;
  
  arg1 = *(struct IntType **)&_swig_go_0; 
  
  struct Type *swig_b0 = (struct Type *)arg1;
  struct Value *swig_b1 = (struct Value *)swig_b0;
  result = (swig_b1)->serialize();
  {
    std::vector< char > * resultptr = (std::vector< char > *)malloc(sizeof(std::vector< char >));
    memmove(resultptr, &result, sizeof(std::vector< char >));
    *(std::vector< char > **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


Value *_wrap_IntType_deserialize_yune_d3d94ab19c12351a(std::vector< char > *_swig_go_0) {
  std::vector< char > arg1 ;
  std::vector< char > *argp1 ;
  Value result;
  Value *_swig_go_result;
  
  
  argp1 = (std::vector< char > *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null std::vector< char >");
  }
  arg1 = (std::vector< char >)*argp1;
  
  
  result = Value::deserialize(arg1);
  {
    Value * resultptr = (Value *)malloc(sizeof(Value));
    memmove(resultptr, &result, sizeof(Value));
    *(Value **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


struct Float *_wrap_new_Float_yune_d3d94ab19c12351a() {
  struct Float *result = 0 ;
  struct Float *_swig_go_result;
  
  
  result = (struct Float *)calloc(1, sizeof(struct Float));
  *(struct Float **)&_swig_go_result = (struct Float *)result; 
  return _swig_go_result;
}


void _wrap_delete_Float_yune_d3d94ab19c12351a(struct Float *_swig_go_0) {
  struct Float *arg1 = (struct Float *) 0 ;
  
  arg1 = *(struct Float **)&_swig_go_0; 
  
  free((char *) arg1);
  
}


std::vector< char > *_wrap_Float_serialize_yune_d3d94ab19c12351a(struct Float *_swig_go_0) {
  struct Float *arg1 = (struct Float *) 0 ;
  std::vector< char > result;
  std::vector< char > *_swig_go_result;
  
  arg1 = *(struct Float **)&_swig_go_0; 
  
  struct Type *swig_b0 = (struct Type *)arg1;
  struct Value *swig_b1 = (struct Value *)swig_b0;
  result = (swig_b1)->serialize();
  {
    std::vector< char > * resultptr = (std::vector< char > *)malloc(sizeof(std::vector< char >));
    memmove(resultptr, &result, sizeof(std::vector< char >));
    *(std::vector< char > **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


Value *_wrap_Float_deserialize_yune_d3d94ab19c12351a(std::vector< char > *_swig_go_0) {
  std::vector< char > arg1 ;
  std::vector< char > *argp1 ;
  Value result;
  Value *_swig_go_result;
  
  
  argp1 = (std::vector< char > *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null std::vector< char >");
  }
  arg1 = (std::vector< char >)*argp1;
  
  
  result = Value::deserialize(arg1);
  {
    Value * resultptr = (Value *)malloc(sizeof(Value));
    memmove(resultptr, &result, sizeof(Value));
    *(Value **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


struct BoolType *_wrap_new_BoolType_yune_d3d94ab19c12351a() {
  struct BoolType *result = 0 ;
  struct BoolType *_swig_go_result;
  
  
  result = (struct BoolType *)calloc(1, sizeof(struct BoolType));
  *(struct BoolType **)&_swig_go_result = (struct BoolType *)result; 
  return _swig_go_result;
}


void _wrap_delete_BoolType_yune_d3d94ab19c12351a(struct BoolType *_swig_go_0) {
  struct BoolType *arg1 = (struct BoolType *) 0 ;
  
  arg1 = *(struct BoolType **)&_swig_go_0; 
  
  free((char *) arg1);
  
}


std::vector< char > *_wrap_BoolType_serialize_yune_d3d94ab19c12351a(struct BoolType *_swig_go_0) {
  struct BoolType *arg1 = (struct BoolType *) 0 ;
  std::vector< char > result;
  std::vector< char > *_swig_go_result;
  
  arg1 = *(struct BoolType **)&_swig_go_0; 
  
  struct Type *swig_b0 = (struct Type *)arg1;
  struct Value *swig_b1 = (struct Value *)swig_b0;
  result = (swig_b1)->serialize();
  {
    std::vector< char > * resultptr = (std::vector< char > *)malloc(sizeof(std::vector< char >));
    memmove(resultptr, &result, sizeof(std::vector< char >));
    *(std::vector< char > **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


Value *_wrap_BoolType_deserialize_yune_d3d94ab19c12351a(std::vector< char > *_swig_go_0) {
  std::vector< char > arg1 ;
  std::vector< char > *argp1 ;
  Value result;
  Value *_swig_go_result;
  
  
  argp1 = (std::vector< char > *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null std::vector< char >");
  }
  arg1 = (std::vector< char >)*argp1;
  
  
  result = Value::deserialize(arg1);
  {
    Value * resultptr = (Value *)malloc(sizeof(Value));
    memmove(resultptr, &result, sizeof(Value));
    *(Value **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


struct StringType *_wrap_new_StringType_yune_d3d94ab19c12351a() {
  struct StringType *result = 0 ;
  struct StringType *_swig_go_result;
  
  
  result = (struct StringType *)calloc(1, sizeof(struct StringType));
  *(struct StringType **)&_swig_go_result = (struct StringType *)result; 
  return _swig_go_result;
}


void _wrap_delete_StringType_yune_d3d94ab19c12351a(struct StringType *_swig_go_0) {
  struct StringType *arg1 = (struct StringType *) 0 ;
  
  arg1 = *(struct StringType **)&_swig_go_0; 
  
  free((char *) arg1);
  
}


std::vector< char > *_wrap_StringType_serialize_yune_d3d94ab19c12351a(struct StringType *_swig_go_0) {
  struct StringType *arg1 = (struct StringType *) 0 ;
  std::vector< char > result;
  std::vector< char > *_swig_go_result;
  
  arg1 = *(struct StringType **)&_swig_go_0; 
  
  struct Type *swig_b0 = (struct Type *)arg1;
  struct Value *swig_b1 = (struct Value *)swig_b0;
  result = (swig_b1)->serialize();
  {
    std::vector< char > * resultptr = (std::vector< char > *)malloc(sizeof(std::vector< char >));
    memmove(resultptr, &result, sizeof(std::vector< char >));
    *(std::vector< char > **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


Value *_wrap_StringType_deserialize_yune_d3d94ab19c12351a(std::vector< char > *_swig_go_0) {
  std::vector< char > arg1 ;
  std::vector< char > *argp1 ;
  Value result;
  Value *_swig_go_result;
  
  
  argp1 = (std::vector< char > *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null std::vector< char >");
  }
  arg1 = (std::vector< char >)*argp1;
  
  
  result = Value::deserialize(arg1);
  {
    Value * resultptr = (Value *)malloc(sizeof(Value));
    memmove(resultptr, &result, sizeof(Value));
    *(Value **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


void _wrap_TupleType_elements_set_yune_d3d94ab19c12351a(struct TupleType *_swig_go_0, std::vector< Type > *_swig_go_1) {
  struct TupleType *arg1 = (struct TupleType *) 0 ;
  std::vector< Type > arg2 ;
  std::vector< Type > *argp2 ;
  
  arg1 = *(struct TupleType **)&_swig_go_0; 
  
  argp2 = (std::vector< Type > *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null std::vector< Type >");
  }
  arg2 = (std::vector< Type >)*argp2;
  
  
  if (arg1) (arg1)->elements = arg2;
  
}


std::vector< Type > *_wrap_TupleType_elements_get_yune_d3d94ab19c12351a(struct TupleType *_swig_go_0) {
  struct TupleType *arg1 = (struct TupleType *) 0 ;
  std::vector< Type > result;
  std::vector< Type > *_swig_go_result;
  
  arg1 = *(struct TupleType **)&_swig_go_0; 
  
  result =  ((arg1)->elements);
  {
    std::vector< Type > * resultptr = (std::vector< Type > *)malloc(sizeof(std::vector< Type >));
    memmove(resultptr, &result, sizeof(std::vector< Type >));
    *(std::vector< Type > **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


struct TupleType *_wrap_new_TupleType_yune_d3d94ab19c12351a() {
  struct TupleType *result = 0 ;
  struct TupleType *_swig_go_result;
  
  
  result = (struct TupleType *)calloc(1, sizeof(struct TupleType));
  *(struct TupleType **)&_swig_go_result = (struct TupleType *)result; 
  return _swig_go_result;
}


void _wrap_delete_TupleType_yune_d3d94ab19c12351a(struct TupleType *_swig_go_0) {
  struct TupleType *arg1 = (struct TupleType *) 0 ;
  
  arg1 = *(struct TupleType **)&_swig_go_0; 
  
  free((char *) arg1);
  
}


std::vector< char > *_wrap_TupleType_serialize_yune_d3d94ab19c12351a(struct TupleType *_swig_go_0) {
  struct TupleType *arg1 = (struct TupleType *) 0 ;
  std::vector< char > result;
  std::vector< char > *_swig_go_result;
  
  arg1 = *(struct TupleType **)&_swig_go_0; 
  
  struct Type *swig_b0 = (struct Type *)arg1;
  struct Value *swig_b1 = (struct Value *)swig_b0;
  result = (swig_b1)->serialize();
  {
    std::vector< char > * resultptr = (std::vector< char > *)malloc(sizeof(std::vector< char >));
    memmove(resultptr, &result, sizeof(std::vector< char >));
    *(std::vector< char > **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


Value *_wrap_TupleType_deserialize_yune_d3d94ab19c12351a(std::vector< char > *_swig_go_0) {
  std::vector< char > arg1 ;
  std::vector< char > *argp1 ;
  Value result;
  Value *_swig_go_result;
  
  
  argp1 = (std::vector< char > *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null std::vector< char >");
  }
  arg1 = (std::vector< char >)*argp1;
  
  
  result = Value::deserialize(arg1);
  {
    Value * resultptr = (Value *)malloc(sizeof(Value));
    memmove(resultptr, &result, sizeof(Value));
    *(Value **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


void _wrap_ListType_element_set_yune_d3d94ab19c12351a(struct ListType *_swig_go_0, Type *_swig_go_1) {
  struct ListType *arg1 = (struct ListType *) 0 ;
  Type arg2 ;
  Type *argp2 ;
  
  arg1 = *(struct ListType **)&_swig_go_0; 
  
  argp2 = (Type *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null Type");
  }
  arg2 = (Type)*argp2;
  
  
  if (arg1) (arg1)->element = arg2;
  
}


Type *_wrap_ListType_element_get_yune_d3d94ab19c12351a(struct ListType *_swig_go_0) {
  struct ListType *arg1 = (struct ListType *) 0 ;
  Type result;
  Type *_swig_go_result;
  
  arg1 = *(struct ListType **)&_swig_go_0; 
  
  result =  ((arg1)->element);
  {
    Type * resultptr = (Type *)malloc(sizeof(Type));
    memmove(resultptr, &result, sizeof(Type));
    *(Type **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


struct ListType *_wrap_new_ListType_yune_d3d94ab19c12351a() {
  struct ListType *result = 0 ;
  struct ListType *_swig_go_result;
  
  
  result = (struct ListType *)calloc(1, sizeof(struct ListType));
  *(struct ListType **)&_swig_go_result = (struct ListType *)result; 
  return _swig_go_result;
}


void _wrap_delete_ListType_yune_d3d94ab19c12351a(struct ListType *_swig_go_0) {
  struct ListType *arg1 = (struct ListType *) 0 ;
  
  arg1 = *(struct ListType **)&_swig_go_0; 
  
  free((char *) arg1);
  
}


std::vector< char > *_wrap_ListType_serialize_yune_d3d94ab19c12351a(struct ListType *_swig_go_0) {
  struct ListType *arg1 = (struct ListType *) 0 ;
  std::vector< char > result;
  std::vector< char > *_swig_go_result;
  
  arg1 = *(struct ListType **)&_swig_go_0; 
  
  struct Type *swig_b0 = (struct Type *)arg1;
  struct Value *swig_b1 = (struct Value *)swig_b0;
  result = (swig_b1)->serialize();
  {
    std::vector< char > * resultptr = (std::vector< char > *)malloc(sizeof(std::vector< char >));
    memmove(resultptr, &result, sizeof(std::vector< char >));
    *(std::vector< char > **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


Value *_wrap_ListType_deserialize_yune_d3d94ab19c12351a(std::vector< char > *_swig_go_0) {
  std::vector< char > arg1 ;
  std::vector< char > *argp1 ;
  Value result;
  Value *_swig_go_result;
  
  
  argp1 = (std::vector< char > *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null std::vector< char >");
  }
  arg1 = (std::vector< char >)*argp1;
  
  
  result = Value::deserialize(arg1);
  {
    Value * resultptr = (Value *)malloc(sizeof(Value));
    memmove(resultptr, &result, sizeof(Value));
    *(Value **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


void _wrap_FnType_argument_set_yune_d3d94ab19c12351a(struct FnType *_swig_go_0, Type *_swig_go_1) {
  struct FnType *arg1 = (struct FnType *) 0 ;
  Type arg2 ;
  Type *argp2 ;
  
  arg1 = *(struct FnType **)&_swig_go_0; 
  
  argp2 = (Type *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null Type");
  }
  arg2 = (Type)*argp2;
  
  
  if (arg1) (arg1)->argument = arg2;
  
}


Type *_wrap_FnType_argument_get_yune_d3d94ab19c12351a(struct FnType *_swig_go_0) {
  struct FnType *arg1 = (struct FnType *) 0 ;
  Type result;
  Type *_swig_go_result;
  
  arg1 = *(struct FnType **)&_swig_go_0; 
  
  result =  ((arg1)->argument);
  {
    Type * resultptr = (Type *)malloc(sizeof(Type));
    memmove(resultptr, &result, sizeof(Type));
    *(Type **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


void _wrap_FnType__return_set_yune_d3d94ab19c12351a(struct FnType *_swig_go_0, Type *_swig_go_1) {
  struct FnType *arg1 = (struct FnType *) 0 ;
  Type arg2 ;
  Type *argp2 ;
  
  arg1 = *(struct FnType **)&_swig_go_0; 
  
  argp2 = (Type *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null Type");
  }
  arg2 = (Type)*argp2;
  
  
  if (arg1) (arg1)->_return = arg2;
  
}


Type *_wrap_FnType__return_get_yune_d3d94ab19c12351a(struct FnType *_swig_go_0) {
  struct FnType *arg1 = (struct FnType *) 0 ;
  Type result;
  Type *_swig_go_result;
  
  arg1 = *(struct FnType **)&_swig_go_0; 
  
  result =  ((arg1)->_return);
  {
    Type * resultptr = (Type *)malloc(sizeof(Type));
    memmove(resultptr, &result, sizeof(Type));
    *(Type **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


struct FnType *_wrap_new_FnType_yune_d3d94ab19c12351a() {
  struct FnType *result = 0 ;
  struct FnType *_swig_go_result;
  
  
  result = (struct FnType *)calloc(1, sizeof(struct FnType));
  *(struct FnType **)&_swig_go_result = (struct FnType *)result; 
  return _swig_go_result;
}


void _wrap_delete_FnType_yune_d3d94ab19c12351a(struct FnType *_swig_go_0) {
  struct FnType *arg1 = (struct FnType *) 0 ;
  
  arg1 = *(struct FnType **)&_swig_go_0; 
  
  free((char *) arg1);
  
}


std::vector< char > *_wrap_FnType_serialize_yune_d3d94ab19c12351a(struct FnType *_swig_go_0) {
  struct FnType *arg1 = (struct FnType *) 0 ;
  std::vector< char > result;
  std::vector< char > *_swig_go_result;
  
  arg1 = *(struct FnType **)&_swig_go_0; 
  
  struct Type *swig_b0 = (struct Type *)arg1;
  struct Value *swig_b1 = (struct Value *)swig_b0;
  result = (swig_b1)->serialize();
  {
    std::vector< char > * resultptr = (std::vector< char > *)malloc(sizeof(std::vector< char >));
    memmove(resultptr, &result, sizeof(std::vector< char >));
    *(std::vector< char > **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


Value *_wrap_FnType_deserialize_yune_d3d94ab19c12351a(std::vector< char > *_swig_go_0) {
  std::vector< char > arg1 ;
  std::vector< char > *argp1 ;
  Value result;
  Value *_swig_go_result;
  
  
  argp1 = (std::vector< char > *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null std::vector< char >");
  }
  arg1 = (std::vector< char >)*argp1;
  
  
  result = Value::deserialize(arg1);
  {
    Value * resultptr = (Value *)malloc(sizeof(Value));
    memmove(resultptr, &result, sizeof(Value));
    *(Value **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


void _wrap_StructType_name_set_yune_d3d94ab19c12351a(struct StructType *_swig_go_0, std::string *_swig_go_1) {
  struct StructType *arg1 = (struct StructType *) 0 ;
  std::string arg2 ;
  std::string *argp2 ;
  
  arg1 = *(struct StructType **)&_swig_go_0; 
  
  argp2 = (std::string *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null std::string");
  }
  arg2 = (std::string)*argp2;
  
  
  if (arg1) (arg1)->name = arg2;
  
}


std::string *_wrap_StructType_name_get_yune_d3d94ab19c12351a(struct StructType *_swig_go_0) {
  struct StructType *arg1 = (struct StructType *) 0 ;
  std::string result;
  std::string *_swig_go_result;
  
  arg1 = *(struct StructType **)&_swig_go_0; 
  
  result =  ((arg1)->name);
  {
    std::string * resultptr = (std::string *)malloc(sizeof(std::string));
    memmove(resultptr, &result, sizeof(std::string));
    *(std::string **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


struct StructType *_wrap_new_StructType_yune_d3d94ab19c12351a() {
  struct StructType *result = 0 ;
  struct StructType *_swig_go_result;
  
  
  result = (struct StructType *)calloc(1, sizeof(struct StructType));
  *(struct StructType **)&_swig_go_result = (struct StructType *)result; 
  return _swig_go_result;
}


void _wrap_delete_StructType_yune_d3d94ab19c12351a(struct StructType *_swig_go_0) {
  struct StructType *arg1 = (struct StructType *) 0 ;
  
  arg1 = *(struct StructType **)&_swig_go_0; 
  
  free((char *) arg1);
  
}


std::vector< char > *_wrap_StructType_serialize_yune_d3d94ab19c12351a(struct StructType *_swig_go_0) {
  struct StructType *arg1 = (struct StructType *) 0 ;
  std::vector< char > result;
  std::vector< char > *_swig_go_result;
  
  arg1 = *(struct StructType **)&_swig_go_0; 
  
  struct Type *swig_b0 = (struct Type *)arg1;
  struct Value *swig_b1 = (struct Value *)swig_b0;
  result = (swig_b1)->serialize();
  {
    std::vector< char > * resultptr = (std::vector< char > *)malloc(sizeof(std::vector< char >));
    memmove(resultptr, &result, sizeof(std::vector< char >));
    *(std::vector< char > **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


Value *_wrap_StructType_deserialize_yune_d3d94ab19c12351a(std::vector< char > *_swig_go_0) {
  std::vector< char > arg1 ;
  std::vector< char > *argp1 ;
  Value result;
  Value *_swig_go_result;
  
  
  argp1 = (std::vector< char > *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null std::vector< char >");
  }
  arg1 = (std::vector< char >)*argp1;
  
  
  result = Value::deserialize(arg1);
  {
    Value * resultptr = (Value *)malloc(sizeof(Value));
    memmove(resultptr, &result, sizeof(Value));
    *(Value **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


struct Expression *_wrap_new_Expression_yune_d3d94ab19c12351a() {
  struct Expression *result = 0 ;
  struct Expression *_swig_go_result;
  
  
  result = (struct Expression *)calloc(1, sizeof(struct Expression));
  *(struct Expression **)&_swig_go_result = (struct Expression *)result; 
  return _swig_go_result;
}


void _wrap_delete_Expression_yune_d3d94ab19c12351a(struct Expression *_swig_go_0) {
  struct Expression *arg1 = (struct Expression *) 0 ;
  
  arg1 = *(struct Expression **)&_swig_go_0; 
  
  free((char *) arg1);
  
}


std::vector< char > *_wrap_Expression_serialize_yune_d3d94ab19c12351a(struct Expression *_swig_go_0) {
  struct Expression *arg1 = (struct Expression *) 0 ;
  std::vector< char > result;
  std::vector< char > *_swig_go_result;
  
  arg1 = *(struct Expression **)&_swig_go_0; 
  
  struct Value *swig_b0 = (struct Value *)arg1;
  result = (swig_b0)->serialize();
  {
    std::vector< char > * resultptr = (std::vector< char > *)malloc(sizeof(std::vector< char >));
    memmove(resultptr, &result, sizeof(std::vector< char >));
    *(std::vector< char > **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


Value *_wrap_Expression_deserialize_yune_d3d94ab19c12351a(std::vector< char > *_swig_go_0) {
  std::vector< char > arg1 ;
  std::vector< char > *argp1 ;
  Value result;
  Value *_swig_go_result;
  
  
  argp1 = (std::vector< char > *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null std::vector< char >");
  }
  arg1 = (std::vector< char >)*argp1;
  
  
  result = Value::deserialize(arg1);
  {
    Value * resultptr = (Value *)malloc(sizeof(Value));
    memmove(resultptr, &result, sizeof(Value));
    *(Value **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


void _wrap_String_value_set_yune_d3d94ab19c12351a(struct String *_swig_go_0, std::string *_swig_go_1) {
  struct String *arg1 = (struct String *) 0 ;
  std::string arg2 ;
  std::string *argp2 ;
  
  arg1 = *(struct String **)&_swig_go_0; 
  
  argp2 = (std::string *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null std::string");
  }
  arg2 = (std::string)*argp2;
  
  
  if (arg1) (arg1)->value = arg2;
  
}


std::string *_wrap_String_value_get_yune_d3d94ab19c12351a(struct String *_swig_go_0) {
  struct String *arg1 = (struct String *) 0 ;
  std::string result;
  std::string *_swig_go_result;
  
  arg1 = *(struct String **)&_swig_go_0; 
  
  result =  ((arg1)->value);
  {
    std::string * resultptr = (std::string *)malloc(sizeof(std::string));
    memmove(resultptr, &result, sizeof(std::string));
    *(std::string **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


struct String *_wrap_new_String_yune_d3d94ab19c12351a() {
  struct String *result = 0 ;
  struct String *_swig_go_result;
  
  
  result = (struct String *)calloc(1, sizeof(struct String));
  *(struct String **)&_swig_go_result = (struct String *)result; 
  return _swig_go_result;
}


void _wrap_delete_String_yune_d3d94ab19c12351a(struct String *_swig_go_0) {
  struct String *arg1 = (struct String *) 0 ;
  
  arg1 = *(struct String **)&_swig_go_0; 
  
  free((char *) arg1);
  
}


std::vector< char > *_wrap_String_serialize_yune_d3d94ab19c12351a(struct String *_swig_go_0) {
  struct String *arg1 = (struct String *) 0 ;
  std::vector< char > result;
  std::vector< char > *_swig_go_result;
  
  arg1 = *(struct String **)&_swig_go_0; 
  
  struct Expression *swig_b0 = (struct Expression *)arg1;
  struct Value *swig_b1 = (struct Value *)swig_b0;
  result = (swig_b1)->serialize();
  {
    std::vector< char > * resultptr = (std::vector< char > *)malloc(sizeof(std::vector< char >));
    memmove(resultptr, &result, sizeof(std::vector< char >));
    *(std::vector< char > **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


Value *_wrap_String_deserialize_yune_d3d94ab19c12351a(std::vector< char > *_swig_go_0) {
  std::vector< char > arg1 ;
  std::vector< char > *argp1 ;
  Value result;
  Value *_swig_go_result;
  
  
  argp1 = (std::vector< char > *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null std::vector< char >");
  }
  arg1 = (std::vector< char >)*argp1;
  
  
  result = Value::deserialize(arg1);
  {
    Value * resultptr = (Value *)malloc(sizeof(Value));
    memmove(resultptr, &result, sizeof(Value));
    *(Value **)&_swig_go_result = resultptr;
  }
  return _swig_go_result;
}


#ifdef __cplusplus
}
#endif

