// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.6
// source: proto/type.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type_Kind int32

const (
	Type_TYPE   Type_Kind = 0 // the type of all types
	Type_INT    Type_Kind = 1
	Type_FLOAT  Type_Kind = 2
	Type_BOOL   Type_Kind = 3
	Type_STRING Type_Kind = 4
	Type_NIL    Type_Kind = 5
	Type_FN     Type_Kind = 6
	Type_TUPLE  Type_Kind = 7
	Type_LIST   Type_Kind = 8
	Type_STRUCT Type_Kind = 9
)

// Enum value maps for Type_Kind.
var (
	Type_Kind_name = map[int32]string{
		0: "TYPE",
		1: "INT",
		2: "FLOAT",
		3: "BOOL",
		4: "STRING",
		5: "NIL",
		6: "FN",
		7: "TUPLE",
		8: "LIST",
		9: "STRUCT",
	}
	Type_Kind_value = map[string]int32{
		"TYPE":   0,
		"INT":    1,
		"FLOAT":  2,
		"BOOL":   3,
		"STRING": 4,
		"NIL":    5,
		"FN":     6,
		"TUPLE":  7,
		"LIST":   8,
		"STRUCT": 9,
	}
)

func (x Type_Kind) Enum() *Type_Kind {
	p := new(Type_Kind)
	*p = x
	return p
}

func (x Type_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_type_proto_enumTypes[0].Descriptor()
}

func (Type_Kind) Type() protoreflect.EnumType {
	return &file_proto_type_proto_enumTypes[0]
}

func (x Type_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type_Kind.Descriptor instead.
func (Type_Kind) EnumDescriptor() ([]byte, []int) {
	return file_proto_type_proto_rawDescGZIP(), []int{0, 0}
}

type Type struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind Type_Kind `protobuf:"varint,1,opt,name=kind,proto3,enum=yune.Type_Kind" json:"kind,omitempty"`
	// Types that are assignable to Detail:
	//
	//	*Type_Fn_
	//	*Type_Tuple_
	//	*Type_List_
	//	*Type_Struct_
	Detail isType_Detail `protobuf_oneof:"Detail"`
}

func (x *Type) Reset() {
	*x = Type{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_type_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type) ProtoMessage() {}

func (x *Type) ProtoReflect() protoreflect.Message {
	mi := &file_proto_type_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type.ProtoReflect.Descriptor instead.
func (*Type) Descriptor() ([]byte, []int) {
	return file_proto_type_proto_rawDescGZIP(), []int{0}
}

func (x *Type) GetKind() Type_Kind {
	if x != nil {
		return x.Kind
	}
	return Type_TYPE
}

func (m *Type) GetDetail() isType_Detail {
	if m != nil {
		return m.Detail
	}
	return nil
}

func (x *Type) GetFn() *Type_Fn {
	if x, ok := x.GetDetail().(*Type_Fn_); ok {
		return x.Fn
	}
	return nil
}

func (x *Type) GetTuple() *Type_Tuple {
	if x, ok := x.GetDetail().(*Type_Tuple_); ok {
		return x.Tuple
	}
	return nil
}

func (x *Type) GetList() *Type_List {
	if x, ok := x.GetDetail().(*Type_List_); ok {
		return x.List
	}
	return nil
}

func (x *Type) GetStruct() *Type_Struct {
	if x, ok := x.GetDetail().(*Type_Struct_); ok {
		return x.Struct
	}
	return nil
}

type isType_Detail interface {
	isType_Detail()
}

type Type_Fn_ struct {
	Fn *Type_Fn `protobuf:"bytes,2,opt,name=fn,proto3,oneof"`
}

type Type_Tuple_ struct {
	Tuple *Type_Tuple `protobuf:"bytes,3,opt,name=tuple,proto3,oneof"`
}

type Type_List_ struct {
	List *Type_List `protobuf:"bytes,4,opt,name=list,proto3,oneof"`
}

type Type_Struct_ struct {
	Struct *Type_Struct `protobuf:"bytes,5,opt,name=struct,proto3,oneof"`
}

func (*Type_Fn_) isType_Detail() {}

func (*Type_Tuple_) isType_Detail() {}

func (*Type_List_) isType_Detail() {}

func (*Type_Struct_) isType_Detail() {}

// Wrapper around multiple messages
type Messages struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages []*anypb.Any `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (x *Messages) Reset() {
	*x = Messages{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_type_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Messages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Messages) ProtoMessage() {}

func (x *Messages) ProtoReflect() protoreflect.Message {
	mi := &file_proto_type_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Messages.ProtoReflect.Descriptor instead.
func (*Messages) Descriptor() ([]byte, []int) {
	return file_proto_type_proto_rawDescGZIP(), []int{1}
}

func (x *Messages) GetMessages() []*anypb.Any {
	if x != nil {
		return x.Messages
	}
	return nil
}

type Type_Fn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArgumentType *Type `protobuf:"bytes,1,opt,name=argumentType,proto3" json:"argumentType,omitempty"`
	ReturnType   *Type `protobuf:"bytes,2,opt,name=returnType,proto3" json:"returnType,omitempty"`
}

func (x *Type_Fn) Reset() {
	*x = Type_Fn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_type_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Type_Fn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type_Fn) ProtoMessage() {}

func (x *Type_Fn) ProtoReflect() protoreflect.Message {
	mi := &file_proto_type_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type_Fn.ProtoReflect.Descriptor instead.
func (*Type_Fn) Descriptor() ([]byte, []int) {
	return file_proto_type_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Type_Fn) GetArgumentType() *Type {
	if x != nil {
		return x.ArgumentType
	}
	return nil
}

func (x *Type_Fn) GetReturnType() *Type {
	if x != nil {
		return x.ReturnType
	}
	return nil
}

type Type_Tuple struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Elements []*Type `protobuf:"bytes,1,rep,name=elements,proto3" json:"elements,omitempty"`
}

func (x *Type_Tuple) Reset() {
	*x = Type_Tuple{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_type_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Type_Tuple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type_Tuple) ProtoMessage() {}

func (x *Type_Tuple) ProtoReflect() protoreflect.Message {
	mi := &file_proto_type_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type_Tuple.ProtoReflect.Descriptor instead.
func (*Type_Tuple) Descriptor() ([]byte, []int) {
	return file_proto_type_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Type_Tuple) GetElements() []*Type {
	if x != nil {
		return x.Elements
	}
	return nil
}

type Type_List struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Element *Type `protobuf:"bytes,1,opt,name=element,proto3" json:"element,omitempty"`
}

func (x *Type_List) Reset() {
	*x = Type_List{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_type_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Type_List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type_List) ProtoMessage() {}

func (x *Type_List) ProtoReflect() protoreflect.Message {
	mi := &file_proto_type_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type_List.ProtoReflect.Descriptor instead.
func (*Type_List) Descriptor() ([]byte, []int) {
	return file_proto_type_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Type_List) GetElement() *Type {
	if x != nil {
		return x.Element
	}
	return nil
}

type Type_Struct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // TODO: fields
}

func (x *Type_Struct) Reset() {
	*x = Type_Struct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_type_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Type_Struct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type_Struct) ProtoMessage() {}

func (x *Type_Struct) ProtoReflect() protoreflect.Message {
	mi := &file_proto_type_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type_Struct.ProtoReflect.Descriptor instead.
func (*Type_Struct) Descriptor() ([]byte, []int) {
	return file_proto_type_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Type_Struct) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_proto_type_proto protoreflect.FileDescriptor

var file_proto_type_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x79, 0x75, 0x6e, 0x65, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xa1, 0x04, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x23, 0x0a, 0x04,
	0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x79, 0x75, 0x6e,
	0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e,
	0x64, 0x12, 0x1f, 0x0a, 0x02, 0x66, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x79, 0x75, 0x6e, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x46, 0x6e, 0x48, 0x00, 0x52, 0x02,
	0x66, 0x6e, 0x12, 0x28, 0x0a, 0x05, 0x74, 0x75, 0x70, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x79, 0x75, 0x6e, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x54, 0x75,
	0x70, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x05, 0x74, 0x75, 0x70, 0x6c, 0x65, 0x12, 0x25, 0x0a, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x79, 0x75, 0x6e,
	0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x00, 0x52, 0x04, 0x6c,
	0x69, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x79, 0x75, 0x6e, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x2e,
	0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x1a, 0x60, 0x0a, 0x02, 0x46, 0x6e, 0x12, 0x2e, 0x0a, 0x0c, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x79,
	0x75, 0x6e, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0c, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2a, 0x0a, 0x0a, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x79, 0x75, 0x6e,
	0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x54, 0x79,
	0x70, 0x65, 0x1a, 0x2f, 0x0a, 0x05, 0x54, 0x75, 0x70, 0x6c, 0x65, 0x12, 0x26, 0x0a, 0x08, 0x65,
	0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x79, 0x75, 0x6e, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x1a, 0x2c, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x07, 0x65,
	0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x79,
	0x75, 0x6e, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x1a, 0x1c, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x6c, 0x0a, 0x04, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x59, 0x50, 0x45, 0x10,
	0x00, 0x12, 0x07, 0x0a, 0x03, 0x49, 0x4e, 0x54, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x46, 0x4c,
	0x4f, 0x41, 0x54, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x4f, 0x4f, 0x4c, 0x10, 0x03, 0x12,
	0x0a, 0x0a, 0x06, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x04, 0x12, 0x07, 0x0a, 0x03, 0x4e,
	0x49, 0x4c, 0x10, 0x05, 0x12, 0x06, 0x0a, 0x02, 0x46, 0x4e, 0x10, 0x06, 0x12, 0x09, 0x0a, 0x05,
	0x54, 0x55, 0x50, 0x4c, 0x45, 0x10, 0x07, 0x12, 0x08, 0x0a, 0x04, 0x4c, 0x49, 0x53, 0x54, 0x10,
	0x08, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54, 0x52, 0x55, 0x43, 0x54, 0x10, 0x09, 0x42, 0x08, 0x0a,
	0x06, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x22, 0x3c, 0x0a, 0x08, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x12, 0x30, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x08, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_type_proto_rawDescOnce sync.Once
	file_proto_type_proto_rawDescData = file_proto_type_proto_rawDesc
)

func file_proto_type_proto_rawDescGZIP() []byte {
	file_proto_type_proto_rawDescOnce.Do(func() {
		file_proto_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_type_proto_rawDescData)
	})
	return file_proto_type_proto_rawDescData
}

var file_proto_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_type_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_type_proto_goTypes = []interface{}{
	(Type_Kind)(0),      // 0: yune.Type.Kind
	(*Type)(nil),        // 1: yune.Type
	(*Messages)(nil),    // 2: yune.Messages
	(*Type_Fn)(nil),     // 3: yune.Type.Fn
	(*Type_Tuple)(nil),  // 4: yune.Type.Tuple
	(*Type_List)(nil),   // 5: yune.Type.List
	(*Type_Struct)(nil), // 6: yune.Type.Struct
	(*anypb.Any)(nil),   // 7: google.protobuf.Any
}
var file_proto_type_proto_depIdxs = []int32{
	0,  // 0: yune.Type.kind:type_name -> yune.Type.Kind
	3,  // 1: yune.Type.fn:type_name -> yune.Type.Fn
	4,  // 2: yune.Type.tuple:type_name -> yune.Type.Tuple
	5,  // 3: yune.Type.list:type_name -> yune.Type.List
	6,  // 4: yune.Type.struct:type_name -> yune.Type.Struct
	7,  // 5: yune.Messages.messages:type_name -> google.protobuf.Any
	1,  // 6: yune.Type.Fn.argumentType:type_name -> yune.Type
	1,  // 7: yune.Type.Fn.returnType:type_name -> yune.Type
	1,  // 8: yune.Type.Tuple.elements:type_name -> yune.Type
	1,  // 9: yune.Type.List.element:type_name -> yune.Type
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_type_proto_init() }
func file_proto_type_proto_init() {
	if File_proto_type_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_type_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Type); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_type_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Messages); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_type_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Type_Fn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_type_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Type_Tuple); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_type_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Type_List); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_type_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Type_Struct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_type_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Type_Fn_)(nil),
		(*Type_Tuple_)(nil),
		(*Type_List_)(nil),
		(*Type_Struct_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_type_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_type_proto_goTypes,
		DependencyIndexes: file_proto_type_proto_depIdxs,
		EnumInfos:         file_proto_type_proto_enumTypes,
		MessageInfos:      file_proto_type_proto_msgTypes,
	}.Build()
	File_proto_type_proto = out.File
	file_proto_type_proto_rawDesc = nil
	file_proto_type_proto_goTypes = nil
	file_proto_type_proto_depIdxs = nil
}
