// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.6
// source: proto/type.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Is:
	//
	//	*Type_Int_
	//	*Type_Float_
	//	*Type_Bool_
	//	*Type_String_
	//	*Type_Fn_
	//	*Type_Tuple_
	//	*Type_List_
	Is isType_Is `protobuf_oneof:"is"`
}

func (x *Type) Reset() {
	*x = Type{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_type_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type) ProtoMessage() {}

func (x *Type) ProtoReflect() protoreflect.Message {
	mi := &file_proto_type_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type.ProtoReflect.Descriptor instead.
func (*Type) Descriptor() ([]byte, []int) {
	return file_proto_type_proto_rawDescGZIP(), []int{0}
}

func (m *Type) GetIs() isType_Is {
	if m != nil {
		return m.Is
	}
	return nil
}

func (x *Type) GetInt() *Type_Int {
	if x, ok := x.GetIs().(*Type_Int_); ok {
		return x.Int
	}
	return nil
}

func (x *Type) GetFloat() *Type_Float {
	if x, ok := x.GetIs().(*Type_Float_); ok {
		return x.Float
	}
	return nil
}

func (x *Type) GetBool() *Type_Bool {
	if x, ok := x.GetIs().(*Type_Bool_); ok {
		return x.Bool
	}
	return nil
}

func (x *Type) GetString_() *Type_String {
	if x, ok := x.GetIs().(*Type_String_); ok {
		return x.String_
	}
	return nil
}

func (x *Type) GetFn() *Type_Fn {
	if x, ok := x.GetIs().(*Type_Fn_); ok {
		return x.Fn
	}
	return nil
}

func (x *Type) GetTuple() *Type_Tuple {
	if x, ok := x.GetIs().(*Type_Tuple_); ok {
		return x.Tuple
	}
	return nil
}

func (x *Type) GetList() *Type_List {
	if x, ok := x.GetIs().(*Type_List_); ok {
		return x.List
	}
	return nil
}

type isType_Is interface {
	isType_Is()
}

type Type_Int_ struct {
	Int *Type_Int `protobuf:"bytes,1,opt,name=int,proto3,oneof"`
}

type Type_Float_ struct {
	Float *Type_Float `protobuf:"bytes,2,opt,name=float,proto3,oneof"`
}

type Type_Bool_ struct {
	Bool *Type_Bool `protobuf:"bytes,3,opt,name=bool,proto3,oneof"`
}

type Type_String_ struct {
	String_ *Type_String `protobuf:"bytes,4,opt,name=string,proto3,oneof"`
}

type Type_Fn_ struct {
	Fn *Type_Fn `protobuf:"bytes,5,opt,name=fn,proto3,oneof"`
}

type Type_Tuple_ struct {
	Tuple *Type_Tuple `protobuf:"bytes,6,opt,name=tuple,proto3,oneof"`
}

type Type_List_ struct {
	List *Type_List `protobuf:"bytes,7,opt,name=list,proto3,oneof"`
}

func (*Type_Int_) isType_Is() {}

func (*Type_Float_) isType_Is() {}

func (*Type_Bool_) isType_Is() {}

func (*Type_String_) isType_Is() {}

func (*Type_Fn_) isType_Is() {}

func (*Type_Tuple_) isType_Is() {}

func (*Type_List_) isType_Is() {}

type Type_Int struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Type_Int) Reset() {
	*x = Type_Int{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_type_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Type_Int) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type_Int) ProtoMessage() {}

func (x *Type_Int) ProtoReflect() protoreflect.Message {
	mi := &file_proto_type_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type_Int.ProtoReflect.Descriptor instead.
func (*Type_Int) Descriptor() ([]byte, []int) {
	return file_proto_type_proto_rawDescGZIP(), []int{0, 0}
}

type Type_Float struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Type_Float) Reset() {
	*x = Type_Float{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_type_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Type_Float) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type_Float) ProtoMessage() {}

func (x *Type_Float) ProtoReflect() protoreflect.Message {
	mi := &file_proto_type_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type_Float.ProtoReflect.Descriptor instead.
func (*Type_Float) Descriptor() ([]byte, []int) {
	return file_proto_type_proto_rawDescGZIP(), []int{0, 1}
}

type Type_Bool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Type_Bool) Reset() {
	*x = Type_Bool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_type_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Type_Bool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type_Bool) ProtoMessage() {}

func (x *Type_Bool) ProtoReflect() protoreflect.Message {
	mi := &file_proto_type_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type_Bool.ProtoReflect.Descriptor instead.
func (*Type_Bool) Descriptor() ([]byte, []int) {
	return file_proto_type_proto_rawDescGZIP(), []int{0, 2}
}

type Type_String struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Type_String) Reset() {
	*x = Type_String{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_type_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Type_String) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type_String) ProtoMessage() {}

func (x *Type_String) ProtoReflect() protoreflect.Message {
	mi := &file_proto_type_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type_String.ProtoReflect.Descriptor instead.
func (*Type_String) Descriptor() ([]byte, []int) {
	return file_proto_type_proto_rawDescGZIP(), []int{0, 3}
}

type Type_Fn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArgumentType *Type `protobuf:"bytes,1,opt,name=argumentType,proto3" json:"argumentType,omitempty"`
	ReturnType   *Type `protobuf:"bytes,2,opt,name=returnType,proto3" json:"returnType,omitempty"`
}

func (x *Type_Fn) Reset() {
	*x = Type_Fn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_type_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Type_Fn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type_Fn) ProtoMessage() {}

func (x *Type_Fn) ProtoReflect() protoreflect.Message {
	mi := &file_proto_type_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type_Fn.ProtoReflect.Descriptor instead.
func (*Type_Fn) Descriptor() ([]byte, []int) {
	return file_proto_type_proto_rawDescGZIP(), []int{0, 4}
}

func (x *Type_Fn) GetArgumentType() *Type {
	if x != nil {
		return x.ArgumentType
	}
	return nil
}

func (x *Type_Fn) GetReturnType() *Type {
	if x != nil {
		return x.ReturnType
	}
	return nil
}

type Type_Tuple struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Elements []*Type `protobuf:"bytes,1,rep,name=elements,proto3" json:"elements,omitempty"`
}

func (x *Type_Tuple) Reset() {
	*x = Type_Tuple{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_type_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Type_Tuple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type_Tuple) ProtoMessage() {}

func (x *Type_Tuple) ProtoReflect() protoreflect.Message {
	mi := &file_proto_type_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type_Tuple.ProtoReflect.Descriptor instead.
func (*Type_Tuple) Descriptor() ([]byte, []int) {
	return file_proto_type_proto_rawDescGZIP(), []int{0, 5}
}

func (x *Type_Tuple) GetElements() []*Type {
	if x != nil {
		return x.Elements
	}
	return nil
}

type Type_List struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Element *Type `protobuf:"bytes,1,opt,name=element,proto3" json:"element,omitempty"`
}

func (x *Type_List) Reset() {
	*x = Type_List{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_type_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Type_List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type_List) ProtoMessage() {}

func (x *Type_List) ProtoReflect() protoreflect.Message {
	mi := &file_proto_type_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type_List.ProtoReflect.Descriptor instead.
func (*Type_List) Descriptor() ([]byte, []int) {
	return file_proto_type_proto_rawDescGZIP(), []int{0, 6}
}

func (x *Type_List) GetElement() *Type {
	if x != nil {
		return x.Element
	}
	return nil
}

var File_proto_type_proto protoreflect.FileDescriptor

var file_proto_type_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x79, 0x75, 0x6e, 0x65, 0x22, 0x83, 0x04, 0x0a, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x22, 0x0a, 0x03, 0x69, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x79, 0x75, 0x6e, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x49, 0x6e, 0x74, 0x48, 0x00,
	0x52, 0x03, 0x69, 0x6e, 0x74, 0x12, 0x28, 0x0a, 0x05, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x79, 0x75, 0x6e, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65,
	0x2e, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x48, 0x00, 0x52, 0x05, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x12,
	0x25, 0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x79, 0x75, 0x6e, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x48, 0x00,
	0x52, 0x04, 0x62, 0x6f, 0x6f, 0x6c, 0x12, 0x2b, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x79, 0x75, 0x6e, 0x65, 0x2e, 0x54, 0x79,
	0x70, 0x65, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x12, 0x1f, 0x0a, 0x02, 0x66, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x79, 0x75, 0x6e, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x46, 0x6e, 0x48, 0x00,
	0x52, 0x02, 0x66, 0x6e, 0x12, 0x28, 0x0a, 0x05, 0x74, 0x75, 0x70, 0x6c, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x79, 0x75, 0x6e, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x2e,
	0x54, 0x75, 0x70, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x05, 0x74, 0x75, 0x70, 0x6c, 0x65, 0x12, 0x25,
	0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x79,
	0x75, 0x6e, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x00, 0x52,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0x1a, 0x05, 0x0a, 0x03, 0x49, 0x6e, 0x74, 0x1a, 0x07, 0x0a, 0x05,
	0x46, 0x6c, 0x6f, 0x61, 0x74, 0x1a, 0x06, 0x0a, 0x04, 0x42, 0x6f, 0x6f, 0x6c, 0x1a, 0x08, 0x0a,
	0x06, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x1a, 0x60, 0x0a, 0x02, 0x46, 0x6e, 0x12, 0x2e, 0x0a,
	0x0c, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x79, 0x75, 0x6e, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x0c, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2a, 0x0a,
	0x0a, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x79, 0x75, 0x6e, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x72,
	0x65, 0x74, 0x75, 0x72, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x1a, 0x2f, 0x0a, 0x05, 0x54, 0x75, 0x70,
	0x6c, 0x65, 0x12, 0x26, 0x0a, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x79, 0x75, 0x6e, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x1a, 0x2c, 0x0a, 0x04, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x24, 0x0a, 0x07, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x79, 0x75, 0x6e, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x07, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x04, 0x0a, 0x02, 0x69, 0x73, 0x42, 0x06,
	0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_type_proto_rawDescOnce sync.Once
	file_proto_type_proto_rawDescData = file_proto_type_proto_rawDesc
)

func file_proto_type_proto_rawDescGZIP() []byte {
	file_proto_type_proto_rawDescOnce.Do(func() {
		file_proto_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_type_proto_rawDescData)
	})
	return file_proto_type_proto_rawDescData
}

var file_proto_type_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_type_proto_goTypes = []interface{}{
	(*Type)(nil),        // 0: yune.Type
	(*Type_Int)(nil),    // 1: yune.Type.Int
	(*Type_Float)(nil),  // 2: yune.Type.Float
	(*Type_Bool)(nil),   // 3: yune.Type.Bool
	(*Type_String)(nil), // 4: yune.Type.String
	(*Type_Fn)(nil),     // 5: yune.Type.Fn
	(*Type_Tuple)(nil),  // 6: yune.Type.Tuple
	(*Type_List)(nil),   // 7: yune.Type.List
}
var file_proto_type_proto_depIdxs = []int32{
	1,  // 0: yune.Type.int:type_name -> yune.Type.Int
	2,  // 1: yune.Type.float:type_name -> yune.Type.Float
	3,  // 2: yune.Type.bool:type_name -> yune.Type.Bool
	4,  // 3: yune.Type.string:type_name -> yune.Type.String
	5,  // 4: yune.Type.fn:type_name -> yune.Type.Fn
	6,  // 5: yune.Type.tuple:type_name -> yune.Type.Tuple
	7,  // 6: yune.Type.list:type_name -> yune.Type.List
	0,  // 7: yune.Type.Fn.argumentType:type_name -> yune.Type
	0,  // 8: yune.Type.Fn.returnType:type_name -> yune.Type
	0,  // 9: yune.Type.Tuple.elements:type_name -> yune.Type
	0,  // 10: yune.Type.List.element:type_name -> yune.Type
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_type_proto_init() }
func file_proto_type_proto_init() {
	if File_proto_type_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_type_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Type); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_type_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Type_Int); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_type_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Type_Float); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_type_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Type_Bool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_type_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Type_String); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_type_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Type_Fn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_type_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Type_Tuple); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_type_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Type_List); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_type_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Type_Int_)(nil),
		(*Type_Float_)(nil),
		(*Type_Bool_)(nil),
		(*Type_String_)(nil),
		(*Type_Fn_)(nil),
		(*Type_Tuple_)(nil),
		(*Type_List_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_type_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_type_proto_goTypes,
		DependencyIndexes: file_proto_type_proto_depIdxs,
		MessageInfos:      file_proto_type_proto_msgTypes,
	}.Build()
	File_proto_type_proto = out.File
	file_proto_type_proto_rawDesc = nil
	file_proto_type_proto_goTypes = nil
	file_proto_type_proto_depIdxs = nil
}
