// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/type.proto

#include "proto/type.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace yune {
constexpr Type_Fn::Type_Fn(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : argumenttype_(nullptr)
  , returntype_(nullptr){}
struct Type_FnDefaultTypeInternal {
  constexpr Type_FnDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~Type_FnDefaultTypeInternal() {}
  union {
    Type_Fn _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT Type_FnDefaultTypeInternal _Type_Fn_default_instance_;
constexpr Type_Tuple::Type_Tuple(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : elements_(){}
struct Type_TupleDefaultTypeInternal {
  constexpr Type_TupleDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~Type_TupleDefaultTypeInternal() {}
  union {
    Type_Tuple _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT Type_TupleDefaultTypeInternal _Type_Tuple_default_instance_;
constexpr Type_List::Type_List(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : element_(nullptr){}
struct Type_ListDefaultTypeInternal {
  constexpr Type_ListDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~Type_ListDefaultTypeInternal() {}
  union {
    Type_List _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT Type_ListDefaultTypeInternal _Type_List_default_instance_;
constexpr Type_Struct::Type_Struct(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : name_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string){}
struct Type_StructDefaultTypeInternal {
  constexpr Type_StructDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~Type_StructDefaultTypeInternal() {}
  union {
    Type_Struct _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT Type_StructDefaultTypeInternal _Type_Struct_default_instance_;
constexpr Type::Type(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : kind_(0)

  , _oneof_case_{}{}
struct TypeDefaultTypeInternal {
  constexpr TypeDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~TypeDefaultTypeInternal() {}
  union {
    Type _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT TypeDefaultTypeInternal _Type_default_instance_;
constexpr Messages::Messages(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : messages_(){}
struct MessagesDefaultTypeInternal {
  constexpr MessagesDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~MessagesDefaultTypeInternal() {}
  union {
    Messages _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT MessagesDefaultTypeInternal _Messages_default_instance_;
}  // namespace yune
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_proto_2ftype_2eproto[6];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_proto_2ftype_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_proto_2ftype_2eproto = nullptr;

const uint32_t TableStruct_proto_2ftype_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::yune::Type_Fn, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::yune::Type_Fn, argumenttype_),
  PROTOBUF_FIELD_OFFSET(::yune::Type_Fn, returntype_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::yune::Type_Tuple, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::yune::Type_Tuple, elements_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::yune::Type_List, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::yune::Type_List, element_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::yune::Type_Struct, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::yune::Type_Struct, name_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::yune::Type, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::yune::Type, _oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::yune::Type, kind_),
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::yune::Type, Detail_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::yune::Messages, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::yune::Messages, messages_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::yune::Type_Fn)},
  { 8, -1, -1, sizeof(::yune::Type_Tuple)},
  { 15, -1, -1, sizeof(::yune::Type_List)},
  { 22, -1, -1, sizeof(::yune::Type_Struct)},
  { 29, -1, -1, sizeof(::yune::Type)},
  { 41, -1, -1, sizeof(::yune::Messages)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::yune::_Type_Fn_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::yune::_Type_Tuple_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::yune::_Type_List_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::yune::_Type_Struct_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::yune::_Type_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::yune::_Messages_default_instance_),
};

const char descriptor_table_protodef_proto_2ftype_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020proto/type.proto\022\004yune\032\031google/protobu"
  "f/any.proto\"\317\003\n\004Type\022\035\n\004kind\030\001 \001(\0162\017.yun"
  "e.Type.Kind\022\033\n\002fn\030\002 \001(\0132\r.yune.Type.FnH\000"
  "\022!\n\005tuple\030\003 \001(\0132\020.yune.Type.TupleH\000\022\037\n\004l"
  "ist\030\004 \001(\0132\017.yune.Type.ListH\000\022#\n\006struct\030\005"
  " \001(\0132\021.yune.Type.StructH\000\032F\n\002Fn\022 \n\014argum"
  "entType\030\001 \001(\0132\n.yune.Type\022\036\n\nreturnType\030"
  "\002 \001(\0132\n.yune.Type\032%\n\005Tuple\022\034\n\010elements\030\001"
  " \003(\0132\n.yune.Type\032#\n\004List\022\033\n\007element\030\001 \001("
  "\0132\n.yune.Type\032\026\n\006Struct\022\014\n\004name\030\001 \001(\t\"l\n"
  "\004Kind\022\010\n\004TYPE\020\000\022\007\n\003INT\020\001\022\t\n\005FLOAT\020\002\022\010\n\004B"
  "OOL\020\003\022\n\n\006STRING\020\004\022\007\n\003NIL\020\005\022\006\n\002FN\020\006\022\t\n\005TU"
  "PLE\020\007\022\010\n\004LIST\020\010\022\n\n\006STRUCT\020\tB\010\n\006Detail\"2\n"
  "\010Messages\022&\n\010messages\030\001 \003(\0132\024.google.pro"
  "tobuf.AnyB\006Z\004./pbb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_proto_2ftype_2eproto_deps[1] = {
  &::descriptor_table_google_2fprotobuf_2fany_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_proto_2ftype_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_2ftype_2eproto = {
  false, false, 585, descriptor_table_protodef_proto_2ftype_2eproto, "proto/type.proto", 
  &descriptor_table_proto_2ftype_2eproto_once, descriptor_table_proto_2ftype_2eproto_deps, 1, 6,
  schemas, file_default_instances, TableStruct_proto_2ftype_2eproto::offsets,
  file_level_metadata_proto_2ftype_2eproto, file_level_enum_descriptors_proto_2ftype_2eproto, file_level_service_descriptors_proto_2ftype_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_proto_2ftype_2eproto_getter() {
  return &descriptor_table_proto_2ftype_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_proto_2ftype_2eproto(&descriptor_table_proto_2ftype_2eproto);
namespace yune {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Type_Kind_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_proto_2ftype_2eproto);
  return file_level_enum_descriptors_proto_2ftype_2eproto[0];
}
bool Type_Kind_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr Type_Kind Type::TYPE;
constexpr Type_Kind Type::INT;
constexpr Type_Kind Type::FLOAT;
constexpr Type_Kind Type::BOOL;
constexpr Type_Kind Type::STRING;
constexpr Type_Kind Type::NIL;
constexpr Type_Kind Type::FN;
constexpr Type_Kind Type::TUPLE;
constexpr Type_Kind Type::LIST;
constexpr Type_Kind Type::STRUCT;
constexpr Type_Kind Type::Kind_MIN;
constexpr Type_Kind Type::Kind_MAX;
constexpr int Type::Kind_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

// ===================================================================

class Type_Fn::_Internal {
 public:
  static const ::yune::Type& argumenttype(const Type_Fn* msg);
  static const ::yune::Type& returntype(const Type_Fn* msg);
};

const ::yune::Type&
Type_Fn::_Internal::argumenttype(const Type_Fn* msg) {
  return *msg->argumenttype_;
}
const ::yune::Type&
Type_Fn::_Internal::returntype(const Type_Fn* msg) {
  return *msg->returntype_;
}
Type_Fn::Type_Fn(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:yune.Type.Fn)
}
Type_Fn::Type_Fn(const Type_Fn& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_argumenttype()) {
    argumenttype_ = new ::yune::Type(*from.argumenttype_);
  } else {
    argumenttype_ = nullptr;
  }
  if (from._internal_has_returntype()) {
    returntype_ = new ::yune::Type(*from.returntype_);
  } else {
    returntype_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:yune.Type.Fn)
}

inline void Type_Fn::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&argumenttype_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&returntype_) -
    reinterpret_cast<char*>(&argumenttype_)) + sizeof(returntype_));
}

Type_Fn::~Type_Fn() {
  // @@protoc_insertion_point(destructor:yune.Type.Fn)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void Type_Fn::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete argumenttype_;
  if (this != internal_default_instance()) delete returntype_;
}

void Type_Fn::ArenaDtor(void* object) {
  Type_Fn* _this = reinterpret_cast< Type_Fn* >(object);
  (void)_this;
}
void Type_Fn::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Type_Fn::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Type_Fn::Clear() {
// @@protoc_insertion_point(message_clear_start:yune.Type.Fn)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && argumenttype_ != nullptr) {
    delete argumenttype_;
  }
  argumenttype_ = nullptr;
  if (GetArenaForAllocation() == nullptr && returntype_ != nullptr) {
    delete returntype_;
  }
  returntype_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Type_Fn::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .yune.Type argumentType = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_argumenttype(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .yune.Type returnType = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_returntype(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Type_Fn::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:yune.Type.Fn)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .yune.Type argumentType = 1;
  if (this->_internal_has_argumenttype()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::argumenttype(this), target, stream);
  }

  // .yune.Type returnType = 2;
  if (this->_internal_has_returntype()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::returntype(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:yune.Type.Fn)
  return target;
}

size_t Type_Fn::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:yune.Type.Fn)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .yune.Type argumentType = 1;
  if (this->_internal_has_argumenttype()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *argumenttype_);
  }

  // .yune.Type returnType = 2;
  if (this->_internal_has_returntype()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *returntype_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Type_Fn::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Type_Fn::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Type_Fn::GetClassData() const { return &_class_data_; }

void Type_Fn::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<Type_Fn *>(to)->MergeFrom(
      static_cast<const Type_Fn &>(from));
}


void Type_Fn::MergeFrom(const Type_Fn& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:yune.Type.Fn)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_argumenttype()) {
    _internal_mutable_argumenttype()->::yune::Type::MergeFrom(from._internal_argumenttype());
  }
  if (from._internal_has_returntype()) {
    _internal_mutable_returntype()->::yune::Type::MergeFrom(from._internal_returntype());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Type_Fn::CopyFrom(const Type_Fn& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yune.Type.Fn)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Type_Fn::IsInitialized() const {
  return true;
}

void Type_Fn::InternalSwap(Type_Fn* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Type_Fn, returntype_)
      + sizeof(Type_Fn::returntype_)
      - PROTOBUF_FIELD_OFFSET(Type_Fn, argumenttype_)>(
          reinterpret_cast<char*>(&argumenttype_),
          reinterpret_cast<char*>(&other->argumenttype_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Type_Fn::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_proto_2ftype_2eproto_getter, &descriptor_table_proto_2ftype_2eproto_once,
      file_level_metadata_proto_2ftype_2eproto[0]);
}

// ===================================================================

class Type_Tuple::_Internal {
 public:
};

Type_Tuple::Type_Tuple(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  elements_(arena) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:yune.Type.Tuple)
}
Type_Tuple::Type_Tuple(const Type_Tuple& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      elements_(from.elements_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:yune.Type.Tuple)
}

inline void Type_Tuple::SharedCtor() {
}

Type_Tuple::~Type_Tuple() {
  // @@protoc_insertion_point(destructor:yune.Type.Tuple)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void Type_Tuple::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Type_Tuple::ArenaDtor(void* object) {
  Type_Tuple* _this = reinterpret_cast< Type_Tuple* >(object);
  (void)_this;
}
void Type_Tuple::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Type_Tuple::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Type_Tuple::Clear() {
// @@protoc_insertion_point(message_clear_start:yune.Type.Tuple)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  elements_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Type_Tuple::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .yune.Type elements = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_elements(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Type_Tuple::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:yune.Type.Tuple)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .yune.Type elements = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_elements_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, this->_internal_elements(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:yune.Type.Tuple)
  return target;
}

size_t Type_Tuple::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:yune.Type.Tuple)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .yune.Type elements = 1;
  total_size += 1UL * this->_internal_elements_size();
  for (const auto& msg : this->elements_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Type_Tuple::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Type_Tuple::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Type_Tuple::GetClassData() const { return &_class_data_; }

void Type_Tuple::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<Type_Tuple *>(to)->MergeFrom(
      static_cast<const Type_Tuple &>(from));
}


void Type_Tuple::MergeFrom(const Type_Tuple& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:yune.Type.Tuple)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  elements_.MergeFrom(from.elements_);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Type_Tuple::CopyFrom(const Type_Tuple& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yune.Type.Tuple)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Type_Tuple::IsInitialized() const {
  return true;
}

void Type_Tuple::InternalSwap(Type_Tuple* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  elements_.InternalSwap(&other->elements_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Type_Tuple::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_proto_2ftype_2eproto_getter, &descriptor_table_proto_2ftype_2eproto_once,
      file_level_metadata_proto_2ftype_2eproto[1]);
}

// ===================================================================

class Type_List::_Internal {
 public:
  static const ::yune::Type& element(const Type_List* msg);
};

const ::yune::Type&
Type_List::_Internal::element(const Type_List* msg) {
  return *msg->element_;
}
Type_List::Type_List(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:yune.Type.List)
}
Type_List::Type_List(const Type_List& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_element()) {
    element_ = new ::yune::Type(*from.element_);
  } else {
    element_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:yune.Type.List)
}

inline void Type_List::SharedCtor() {
element_ = nullptr;
}

Type_List::~Type_List() {
  // @@protoc_insertion_point(destructor:yune.Type.List)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void Type_List::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete element_;
}

void Type_List::ArenaDtor(void* object) {
  Type_List* _this = reinterpret_cast< Type_List* >(object);
  (void)_this;
}
void Type_List::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Type_List::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Type_List::Clear() {
// @@protoc_insertion_point(message_clear_start:yune.Type.List)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && element_ != nullptr) {
    delete element_;
  }
  element_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Type_List::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .yune.Type element = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_element(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Type_List::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:yune.Type.List)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .yune.Type element = 1;
  if (this->_internal_has_element()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::element(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:yune.Type.List)
  return target;
}

size_t Type_List::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:yune.Type.List)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .yune.Type element = 1;
  if (this->_internal_has_element()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *element_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Type_List::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Type_List::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Type_List::GetClassData() const { return &_class_data_; }

void Type_List::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<Type_List *>(to)->MergeFrom(
      static_cast<const Type_List &>(from));
}


void Type_List::MergeFrom(const Type_List& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:yune.Type.List)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_element()) {
    _internal_mutable_element()->::yune::Type::MergeFrom(from._internal_element());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Type_List::CopyFrom(const Type_List& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yune.Type.List)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Type_List::IsInitialized() const {
  return true;
}

void Type_List::InternalSwap(Type_List* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(element_, other->element_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Type_List::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_proto_2ftype_2eproto_getter, &descriptor_table_proto_2ftype_2eproto_once,
      file_level_metadata_proto_2ftype_2eproto[2]);
}

// ===================================================================

class Type_Struct::_Internal {
 public:
};

Type_Struct::Type_Struct(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:yune.Type.Struct)
}
Type_Struct::Type_Struct(const Type_Struct& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_name().empty()) {
    name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_name(), 
      GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:yune.Type.Struct)
}

inline void Type_Struct::SharedCtor() {
name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Type_Struct::~Type_Struct() {
  // @@protoc_insertion_point(destructor:yune.Type.Struct)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void Type_Struct::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void Type_Struct::ArenaDtor(void* object) {
  Type_Struct* _this = reinterpret_cast< Type_Struct* >(object);
  (void)_this;
}
void Type_Struct::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Type_Struct::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Type_Struct::Clear() {
// @@protoc_insertion_point(message_clear_start:yune.Type.Struct)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Type_Struct::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_name();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "yune.Type.Struct.name"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Type_Struct::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:yune.Type.Struct)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "yune.Type.Struct.name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_name(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:yune.Type.Struct)
  return target;
}

size_t Type_Struct::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:yune.Type.Struct)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Type_Struct::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Type_Struct::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Type_Struct::GetClassData() const { return &_class_data_; }

void Type_Struct::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<Type_Struct *>(to)->MergeFrom(
      static_cast<const Type_Struct &>(from));
}


void Type_Struct::MergeFrom(const Type_Struct& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:yune.Type.Struct)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _internal_set_name(from._internal_name());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Type_Struct::CopyFrom(const Type_Struct& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yune.Type.Struct)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Type_Struct::IsInitialized() const {
  return true;
}

void Type_Struct::InternalSwap(Type_Struct* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &name_, lhs_arena,
      &other->name_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata Type_Struct::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_proto_2ftype_2eproto_getter, &descriptor_table_proto_2ftype_2eproto_once,
      file_level_metadata_proto_2ftype_2eproto[3]);
}

// ===================================================================

class Type::_Internal {
 public:
  static const ::yune::Type_Fn& fn(const Type* msg);
  static const ::yune::Type_Tuple& tuple(const Type* msg);
  static const ::yune::Type_List& list(const Type* msg);
  static const ::yune::Type_Struct& struct_(const Type* msg);
};

const ::yune::Type_Fn&
Type::_Internal::fn(const Type* msg) {
  return *msg->Detail_.fn_;
}
const ::yune::Type_Tuple&
Type::_Internal::tuple(const Type* msg) {
  return *msg->Detail_.tuple_;
}
const ::yune::Type_List&
Type::_Internal::list(const Type* msg) {
  return *msg->Detail_.list_;
}
const ::yune::Type_Struct&
Type::_Internal::struct_(const Type* msg) {
  return *msg->Detail_.struct__;
}
void Type::set_allocated_fn(::yune::Type_Fn* fn) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_Detail();
  if (fn) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::yune::Type_Fn>::GetOwningArena(fn);
    if (message_arena != submessage_arena) {
      fn = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, fn, submessage_arena);
    }
    set_has_fn();
    Detail_.fn_ = fn;
  }
  // @@protoc_insertion_point(field_set_allocated:yune.Type.fn)
}
void Type::set_allocated_tuple(::yune::Type_Tuple* tuple) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_Detail();
  if (tuple) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::yune::Type_Tuple>::GetOwningArena(tuple);
    if (message_arena != submessage_arena) {
      tuple = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, tuple, submessage_arena);
    }
    set_has_tuple();
    Detail_.tuple_ = tuple;
  }
  // @@protoc_insertion_point(field_set_allocated:yune.Type.tuple)
}
void Type::set_allocated_list(::yune::Type_List* list) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_Detail();
  if (list) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::yune::Type_List>::GetOwningArena(list);
    if (message_arena != submessage_arena) {
      list = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, list, submessage_arena);
    }
    set_has_list();
    Detail_.list_ = list;
  }
  // @@protoc_insertion_point(field_set_allocated:yune.Type.list)
}
void Type::set_allocated_struct_(::yune::Type_Struct* struct_) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_Detail();
  if (struct_) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::yune::Type_Struct>::GetOwningArena(struct_);
    if (message_arena != submessage_arena) {
      struct_ = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, struct_, submessage_arena);
    }
    set_has_struct_();
    Detail_.struct__ = struct_;
  }
  // @@protoc_insertion_point(field_set_allocated:yune.Type.struct)
}
Type::Type(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:yune.Type)
}
Type::Type(const Type& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  kind_ = from.kind_;
  clear_has_Detail();
  switch (from.Detail_case()) {
    case kFn: {
      _internal_mutable_fn()->::yune::Type_Fn::MergeFrom(from._internal_fn());
      break;
    }
    case kTuple: {
      _internal_mutable_tuple()->::yune::Type_Tuple::MergeFrom(from._internal_tuple());
      break;
    }
    case kList: {
      _internal_mutable_list()->::yune::Type_List::MergeFrom(from._internal_list());
      break;
    }
    case kStruct: {
      _internal_mutable_struct_()->::yune::Type_Struct::MergeFrom(from._internal_struct_());
      break;
    }
    case DETAIL_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:yune.Type)
}

inline void Type::SharedCtor() {
kind_ = 0;
clear_has_Detail();
}

Type::~Type() {
  // @@protoc_insertion_point(destructor:yune.Type)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void Type::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (has_Detail()) {
    clear_Detail();
  }
}

void Type::ArenaDtor(void* object) {
  Type* _this = reinterpret_cast< Type* >(object);
  (void)_this;
}
void Type::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Type::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Type::clear_Detail() {
// @@protoc_insertion_point(one_of_clear_start:yune.Type)
  switch (Detail_case()) {
    case kFn: {
      if (GetArenaForAllocation() == nullptr) {
        delete Detail_.fn_;
      }
      break;
    }
    case kTuple: {
      if (GetArenaForAllocation() == nullptr) {
        delete Detail_.tuple_;
      }
      break;
    }
    case kList: {
      if (GetArenaForAllocation() == nullptr) {
        delete Detail_.list_;
      }
      break;
    }
    case kStruct: {
      if (GetArenaForAllocation() == nullptr) {
        delete Detail_.struct__;
      }
      break;
    }
    case DETAIL_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = DETAIL_NOT_SET;
}


void Type::Clear() {
// @@protoc_insertion_point(message_clear_start:yune.Type)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  kind_ = 0;
  clear_Detail();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Type::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .yune.Type.Kind kind = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_kind(static_cast<::yune::Type_Kind>(val));
        } else
          goto handle_unusual;
        continue;
      // .yune.Type.Fn fn = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_fn(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .yune.Type.Tuple tuple = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_tuple(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .yune.Type.List list = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_list(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .yune.Type.Struct struct = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_struct_(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Type::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:yune.Type)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .yune.Type.Kind kind = 1;
  if (this->_internal_kind() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->_internal_kind(), target);
  }

  // .yune.Type.Fn fn = 2;
  if (_internal_has_fn()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::fn(this), target, stream);
  }

  // .yune.Type.Tuple tuple = 3;
  if (_internal_has_tuple()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        3, _Internal::tuple(this), target, stream);
  }

  // .yune.Type.List list = 4;
  if (_internal_has_list()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        4, _Internal::list(this), target, stream);
  }

  // .yune.Type.Struct struct = 5;
  if (_internal_has_struct_()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        5, _Internal::struct_(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:yune.Type)
  return target;
}

size_t Type::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:yune.Type)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .yune.Type.Kind kind = 1;
  if (this->_internal_kind() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_kind());
  }

  switch (Detail_case()) {
    // .yune.Type.Fn fn = 2;
    case kFn: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *Detail_.fn_);
      break;
    }
    // .yune.Type.Tuple tuple = 3;
    case kTuple: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *Detail_.tuple_);
      break;
    }
    // .yune.Type.List list = 4;
    case kList: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *Detail_.list_);
      break;
    }
    // .yune.Type.Struct struct = 5;
    case kStruct: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *Detail_.struct__);
      break;
    }
    case DETAIL_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Type::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Type::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Type::GetClassData() const { return &_class_data_; }

void Type::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<Type *>(to)->MergeFrom(
      static_cast<const Type &>(from));
}


void Type::MergeFrom(const Type& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:yune.Type)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_kind() != 0) {
    _internal_set_kind(from._internal_kind());
  }
  switch (from.Detail_case()) {
    case kFn: {
      _internal_mutable_fn()->::yune::Type_Fn::MergeFrom(from._internal_fn());
      break;
    }
    case kTuple: {
      _internal_mutable_tuple()->::yune::Type_Tuple::MergeFrom(from._internal_tuple());
      break;
    }
    case kList: {
      _internal_mutable_list()->::yune::Type_List::MergeFrom(from._internal_list());
      break;
    }
    case kStruct: {
      _internal_mutable_struct_()->::yune::Type_Struct::MergeFrom(from._internal_struct_());
      break;
    }
    case DETAIL_NOT_SET: {
      break;
    }
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Type::CopyFrom(const Type& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yune.Type)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Type::IsInitialized() const {
  return true;
}

void Type::InternalSwap(Type* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(kind_, other->kind_);
  swap(Detail_, other->Detail_);
  swap(_oneof_case_[0], other->_oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata Type::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_proto_2ftype_2eproto_getter, &descriptor_table_proto_2ftype_2eproto_once,
      file_level_metadata_proto_2ftype_2eproto[4]);
}

// ===================================================================

class Messages::_Internal {
 public:
};

void Messages::clear_messages() {
  messages_.Clear();
}
Messages::Messages(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  messages_(arena) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:yune.Messages)
}
Messages::Messages(const Messages& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      messages_(from.messages_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:yune.Messages)
}

inline void Messages::SharedCtor() {
}

Messages::~Messages() {
  // @@protoc_insertion_point(destructor:yune.Messages)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void Messages::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Messages::ArenaDtor(void* object) {
  Messages* _this = reinterpret_cast< Messages* >(object);
  (void)_this;
}
void Messages::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Messages::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Messages::Clear() {
// @@protoc_insertion_point(message_clear_start:yune.Messages)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  messages_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Messages::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .google.protobuf.Any messages = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_messages(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Messages::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:yune.Messages)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .google.protobuf.Any messages = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_messages_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, this->_internal_messages(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:yune.Messages)
  return target;
}

size_t Messages::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:yune.Messages)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .google.protobuf.Any messages = 1;
  total_size += 1UL * this->_internal_messages_size();
  for (const auto& msg : this->messages_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Messages::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Messages::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Messages::GetClassData() const { return &_class_data_; }

void Messages::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<Messages *>(to)->MergeFrom(
      static_cast<const Messages &>(from));
}


void Messages::MergeFrom(const Messages& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:yune.Messages)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  messages_.MergeFrom(from.messages_);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Messages::CopyFrom(const Messages& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yune.Messages)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Messages::IsInitialized() const {
  return true;
}

void Messages::InternalSwap(Messages* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  messages_.InternalSwap(&other->messages_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Messages::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_proto_2ftype_2eproto_getter, &descriptor_table_proto_2ftype_2eproto_once,
      file_level_metadata_proto_2ftype_2eproto[5]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace yune
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::yune::Type_Fn* Arena::CreateMaybeMessage< ::yune::Type_Fn >(Arena* arena) {
  return Arena::CreateMessageInternal< ::yune::Type_Fn >(arena);
}
template<> PROTOBUF_NOINLINE ::yune::Type_Tuple* Arena::CreateMaybeMessage< ::yune::Type_Tuple >(Arena* arena) {
  return Arena::CreateMessageInternal< ::yune::Type_Tuple >(arena);
}
template<> PROTOBUF_NOINLINE ::yune::Type_List* Arena::CreateMaybeMessage< ::yune::Type_List >(Arena* arena) {
  return Arena::CreateMessageInternal< ::yune::Type_List >(arena);
}
template<> PROTOBUF_NOINLINE ::yune::Type_Struct* Arena::CreateMaybeMessage< ::yune::Type_Struct >(Arena* arena) {
  return Arena::CreateMessageInternal< ::yune::Type_Struct >(arena);
}
template<> PROTOBUF_NOINLINE ::yune::Type* Arena::CreateMaybeMessage< ::yune::Type >(Arena* arena) {
  return Arena::CreateMessageInternal< ::yune::Type >(arena);
}
template<> PROTOBUF_NOINLINE ::yune::Messages* Arena::CreateMaybeMessage< ::yune::Messages >(Arena* arena) {
  return Arena::CreateMessageInternal< ::yune::Messages >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
